### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by M3tthew** [Ph1b/MaterialAudiobookPlayer#100]
Widget on my homescreen often not respond for touches. and i need to open app and start playing book from it

**Comment by M3tthew** [comment]
It doesn't works from time to time. it's not completely dead. it happens only when it paused. unlocking screen. i will test it about moving tomorrow

**Comment by JoshGraham** [comment]
Hmm... In my case, pause all music, then use widget 5 or 10 minutes later = works fine.
Maybe 30 minutes or more? = widget unresponsive.
Maybe not reproducible under other circumstances as logs show nothing.
Maybe testing it out after longer than 30 minutes or so would produce that?

And interesting thing is, make second widget in the launcher next to unresponsive(first) one.
Use second widget(which works) to play/pause = in sync with first widget.
Still, first one is unresponsive.
Maybe widget kind of disconnects with app after long duration of time, and never connects back?
As second widget is fine to play/pause.

**Comment by JoshGraham** [comment]
Hmm, rebooting the device fixes it.

Maybe widget needed a good refreshing. ;-)

**Comment by Ph1b** [comment]
Can you check if this still persists here?
https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly-1420409297

**Comment by M3tthew** [comment]
yes i will try it tomorrow

2015-01-05 0:16 GMT+02:00 Paul Woitaschek <notifications@github.com>:

**Comment by JoshGraham** [comment]
Sure thing. Going to take time to try to reproduce that issue, or fails to,
then it means it's fixed.

But, initial test run, some weird behavior of widget happened.

Attached log.

Video link(gdrive)
https://docs.google.com/file/d/0Bx63yOoCrPyGYVQ1WGVNcUJyUW8/edit?usp=docslist_api

**Comment by Ph1b** [comment]
Pls test with new version: https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly-1420418766

**Comment by JoshGraham** [comment]
Yes. New version has no weird behavior.

Though, To test #100 issue, widget's gonna stay at launcher for sometime.

Josh

**Comment by M3tthew** [comment]
looks like it works good

**Comment by isindir** [comment]
Installed version 1.5.3 from F-Droid. Android 4.2.2. Kernel 3.4.5.
Widget on a sleep display starts to flicker after playing some time, as well as sound disappears. When I wake it up most of the time application main window and notification icon disappears, so I have to restart application. After this playback position often not at the same place where it has stopped.
- Should I log a new ticket for this ?
- May be setting to disable sleep mode widget can be added ?

Thanks

**Comment by Ph1b** [comment]
Please open a new ticket with new requests. Also I dont get what you mean with a 'sleep display' or the problem in general. Pls explain a bit more, thx :)
