### ISSUE TITLE
Suggestion : Sleep timer like alarm clock.

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#101]
Weird suggestion.

I sometimes forget to set sleep timer while in bed.

Preset of daily sleep timer like alarm clock works?

Hmm.

Unnecessarily complex feature, I know.

**Comment by Ph1b** [comment]
Thats to much of a configuration hastle. I like to keep it simple and hav a click on the timer to switch it on / off.
