### ISSUE TITLE
Feature request: Adding Characters

### ISSUE THREAD

**Issue by Yma981** [Ph1b/MaterialAudiobookPlayer#103]
Adding Characters in order to keep track of the characters in a book.

**Comment by Ph1b** [comment]
Can you explain what you mean by 'characters'?

**Comment by Yma981** [comment]
I mean by it: The imaginary persons represented in a work of fiction, in this case the Audiobooks, in order to keep track of the Characters of the book and their development, especially if the book has a plethora of them.

**Comment by Ph1b** [comment]
I still don't get it. How would that look like? Can you describe what that
would do and how it would look like? Maybe with a paint sketch? How can the
player know about the characters in a book? Like having a 'notes' field in
free text?
Am 05.01.2015 07:04 schrieb "Yma981" <notifications@github.com>:

**Comment by Yma981** [comment]
Yes it imagine it as a form where the listener can manually add them As free text

Character Name:
Role:
Description:

**Comment by MuchosMuffins** [comment]
I think this i nothing for this Version of player. It's nothing that everybody will use. Perhaps it is something for an Pro Version or something like that. 
He will list Characters of the Book for himself, to get to know what role they have and something like that.

**Comment by Ph1b** [comment]
I think of that as a feature overkill. So sorry, I want to keep it simple and possible.
