### ISSUE TITLE
Widget font color

### ISSUE THREAD

**Issue by CronusXP** [Ph1b/MaterialAudiobookPlayer#106]
The font of track information is black, on the dark gray background, making it almost invisible. That happens both on the widget and the notification. 
In the screenshot on Google play of Material Audiobook Player , it is white font on dark background. So it is only me or not? Hope it will be fixed in the next update.

Android version: 4.4.2
Phone: Huawei H60-L11 (so called Honor 6)
OEM UI: EMUI 3.0

**Comment by Ph1b** [comment]
Thanks for the feedback. Does this still occur here?
https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly-1420418766

**Comment by CronusXP** [comment]
Great, works like a charm!
