### ISSUE TITLE
Playback Doesn't Pause For Google Maps Voice Navigation 

### ISSUE THREAD

**Issue by innesst** [Ph1b/MaterialAudiobookPlayer#107]
Nexus 5
Android 5.0.1
Playing through bluetooth

If Google Maps voice navigation is active, playback will not pause and both the voice navigation and Material Player audio will be heard at the same time. I believe this also occurs during the beep noise if I receive a text or e-mail (other players pause for a moment for those). 

Properly pauses for Google Now voice entry and feedback, and for phone calls (ringing or active).

**Comment by Ph1b** [comment]
This is intended behavior. The player should lower volume when the audiofocus gets lost temporary (https://github.com/Ph1b/MaterialAudiobookPlayer/blob/master/audiobook/src/main/java/de/ph1b/audiobook/service/AudioPlayerService.java#L146) and raise it when it gets the focus back (https://github.com/Ph1b/MaterialAudiobookPlayer/blob/master/audiobook/src/main/java/de/ph1b/audiobook/service/AudioPlayerService.java#L134).

**Comment by innesst** [comment]
Thanks for the response. Would it be possible to have an option to reduce volume or pause? I have a hard time hearing the navigation, and really can't hear the player at all, causing me to need to rewind every time. I understand not pausing for notification tones, but navigation can sometimes go on for maybe 20 seconds, and/or multiple times in a short time. It is very distracting while driving.

**Comment by Ph1b** [comment]
Done as of d0537b9ae7a142475fe011c492bcb64fe86f2648
