### ISSUE TITLE
Feature request: standalone wear support

### ISSUE THREAD

**Issue by brad** [Ph1b/MaterialAudiobookPlayer#110]
Thank you for the excellent app! The only thing that I would appreciate to make it better is an android wear module that lets me play audiobooks when the watch is disconnected.
It turns out that when I manually install the full app directly to the watch, it already works perfectly! The interface is actually almost completely usable but it could use some massaging to fit the tiny screen better.
I believe this is the only current solution (I looked at a lot of other apps) for playing audiobooks (and saving position) via the standalone smartwatch.
Until this feature exists, if anyone wishes to replicate my success, here's what I did:
* Download the app from [Fdroid](https://f-droid.org/repo/de.ph1b.audiobook_28.apk)
* Connect adb to the smartwatch and push the apk: `adb install de.ph1b.audiobook_28.apk`
* Push your audiobook to the smartwatch: `adb push /path/to/audiobook/ /sdcard/path/to/audiobook/`

That's it! Now you can open the app on the watch and add the book there. The app appears to freeze up while the book is being added, but after about a half hour it finishes and you can start listening to the book on a bluetooth headset. Thanks again! :neckbeard:

**Comment by Ph1b** [comment]
Cool that you made this work. I dont have a watch on my own and dont know anyone having one, so this is not one of my priorities. But if someone wants to code it, feel free to contribute, thx :)
