### ISSUE TITLE
Headphone & Bluetooth Control Support

### ISSUE THREAD

**Issue by ministryofsillywalks** [Ph1b/MaterialAudiobookPlayer#111]
I have a pair of headphones with a button which normaly controls media play/pause however not in material audiobook player.

Also i have a pebble smartwatch and using musicboss I can control all media applications play/pause volume etc. however Material Audiobook Player is not recognized as a media application so I can't control it.

Would be great if you could add support for this.

**Comment by blakadder** [comment]
+1 for the regular headphone play/pause support

**Comment by Ph1b** [comment]
Good morning. You both use Android 5? This is no new feature request, this is a bug report.
This is implemented but somehow not working.

So 2 questions:
Which android version do you use?
Do the controls work when screen is unlocked?

**Comment by ministryofsillywalks** [comment]
Running Android 5.0.1 on a Nexus 5.
Having the screen unlocked changes nothing. (Neither Headphone Button nor Pebble Smartwatch work)

**Comment by blakadder** [comment]
Running Android 4.4.4 
Control doesn't work on unlocked or locked screen.

Note: the headphone plug/unplug pause/resume feature is working correctly

**Comment by Ph1b** [comment]
Do Next/Prev buttons work? I redirected them to be a fast forward/skip.

**Comment by blakadder** [comment]
I'm using the wired headset with a single button, so play/pause only for me

**Comment by ministryofsillywalks** [comment]
Same for me. One button headset.
Am 16.01.2015 11:07 schrieb "blakadder" <notifications@github.com>:
