### ISSUE TITLE
Request: Play Mono files on Right & Left

### ISSUE THREAD

**Issue by ministryofsillywalks** [Ph1b/MaterialAudiobookPlayer#112]
I have a few audiobooks which are recorded in Mono (or maybe just one channel)
It would be great to have the option to have this play on both sides and not just one.

**Comment by Ph1b** [comment]
Can you send me a file where that occurs?

**Comment by ministryofsillywalks** [comment]
Here you go:
https://www.dropbox.com/s/wbelv50gv4wlaq7/DTMH004.mp3?dl=0

**Comment by dark-seizo** [comment]
Tested this on the latest git version and F-Droid version, audio is playing on both sides for me.
