### ISSUE TITLE
Plus button makes it hard to delete newest audiobook

### ISSUE THREAD

**Issue by lightonflux** [Ph1b/MaterialAudiobookPlayer#113]
If you have many audiobooks (>=6) and it is a straight number, so one book is overshadowed by the plus button, then it is not possible to change or delete it. 

There is a workaround: change the order of the books (long press on audiobook).

I saw that other material apps like "Simple Explorer" ([also FOSS](https://github.com/DF1E/SimpleExplorer)) hide the button in some situations. But i don't know the pattern/trigger, it is not very obvious.

I don't think the current solution or the situation of Simple Explorer are good usability. But it might be better than the current situation in MAP.

BTW: I would understand if this will get tagged "wontfix". It more a problem with the Material Guidelines and the hover buttons in general  than this app.

**Comment by Yma981** [comment]
+1

**Comment by Ph1b** [comment]
Do you have an idea, what to do on this? I thought about putting the menu button to the left but that looks ugly.

**Comment by Yma981** [comment]
A probable solution
you can put the + button next to the (three buttons  "Setting") on the top right

**Comment by Ph1b** [comment]
As of the latest nightlys this problem has been resolved by itself (No more add button)
