### ISSUE TITLE
Material Player crashes after adding a book

### ISSUE THREAD

**Issue by Yma981** [Ph1b/MaterialAudiobookPlayer#116]
Material Design Crashes after adding a book and all the reading progress of the last book resets to ZERO
Lastest Version of Material Player
OmniRom Android 4.4.4
Samsung Note 1 N7000

**Comment by Ph1b** [comment]
Could you please send me a file for which this one crashes? Is there a crash report? Did you submit it to the playstore?

**Comment by Yma981** [comment]
Yes i did submit a crash report.

MAP crashes everytime i add any new book (Any type, MP3 and other types).

**Comment by Ph1b** [comment]
Since there is no more feedback, I assume this is fixed. If not, please reopen.
