### ISSUE TITLE
Audiobook in multiple mp3s shows only the length of current mp3 playing

### ISSUE THREAD

**Issue by dark-seizo** [Ph1b/MaterialAudiobookPlayer#117]
Audiobooks in multiple .mp3 format shows the length of the book as the length of the current mp3 file in the main view, not the entire length of the book (the aggregate of all the mp3 files length).

**Comment by Yma981** [comment]
i requested a feature to add (customizable in the setting) time information but was rejected by the Developer
https://github.com/Ph1b/MaterialAudiobookPlayer/issues/95

**Comment by parker80** [comment]
I would love this feature as well. For me, it's far more useful to show the entire book progress, rather than just the current track. I think this would work better as the default setting.
