### ISSUE TITLE
Multiple Bookmarks Support

### ISSUE THREAD

**Issue by ArchUser** [Ph1b/MaterialAudiobookPlayer#120]
Something like rockbox where you can create multiple bookmarks per book. It would be cool if you could rename the bookmark as well so if there is a point you want to refer to later.

**Comment by Yma981** [comment]
please check:
https://github.com/Ph1b/MaterialAudiobookPlayer/issues/80

**Comment by Ph1b** [comment]
Will be included in the upcoming version.
