### ISSUE TITLE
Backup bookmarks/preferences

### ISSUE THREAD

**Issue by ArchUser** [Ph1b/MaterialAudiobookPlayer#121]
This one is big for me because I update/switch roms from time to time and everything gets wiped so I have to manually figure out where I was on all the books I have. It would be nice if you could backcup the bookmarks and preferences (preferences isn't that essential but it'd be nice) to file or cloud (dropbox, drive etc.).

**Comment by Ph1b** [comment]
Preferences  should be backed up to google.
Bookmarks, books etc preferences will be permanent from version 2.0 on. Works in [nightly](https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly15-03-19-16-31).
