### ISSUE TITLE
1.5.4-rc1 // Freaky Force Crash

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#124]
Couldn't reproduce.
AndroidRuntime( 6978): FATAL EXCEPTION: 
Might be user misconfiguration.
Attached logfile just in case.

logfile(phone)
https://gist.githubusercontent.com/JoshGraham/e44d61397023ab001d62/raw/6ae00b6ea26f8a714d9def80f3ed5bfca151d45c/gistfile1.txt

logfile(tablet)
https://gist.githubusercontent.com/JoshGraham/174efcabd291d0b35199/raw/396911fe871abf3b866aede1ec1b29a2299ccb62/gistfile1.txt

**Comment by Ph1b** [comment]
If this still happens in https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/v1.5.4-rc2 please reopen this or open a new ticket.
