### ISSUE TITLE
1.5.4-rc1 // (UX Suggestion) Keyboard, + button, "ABORT" button 

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#125]
Like the closed #4 , #32 .

But this time, bookmark.

Inconsistent keyboard exprience in phone and tablet.

Though, it could be misconfiguration on user's devices.
---------------logfile--------------------
Phone (Keyboard shows up tapping bookmark)
https://gist.githubusercontent.com/JoshGraham/696dd376e6db30089576/raw/a6f24f54068638b94f0e5ed90a42b5e5f4d8834b/gistfile1.txt

Tablet (Keyboard not shoing up tapping bookmark)
https://gist.githubusercontent.com/JoshGraham/79a38ab01025a416f2e8/raw/bc2770ce9dd3f4a9f4ff1737ab4e99711d76fd57/gistfile1.txt
---------------logfile end--------------------

-------------------------
UX Case 1
User tends to bookmark with their own "Bookmark name", UX would flow like below

Tablet (Keyboard showing up automatically) 
User taps bookmark button
(Keyboard automatically shows up when bookmark button is clicked. To go back, user taps the back utton to hide the keyboard, then "ABORT" button is tapped to go back)
User types
User bookmarks by + button
User hides the keyboard by hitting back button
User taps "ABORT" to get back to library

Phone (Keyboard not showing up automatically) 
User taps bookmark button
(Keyboard not automatically shows up when bookmark button is clicked. To go back, user taps "ABORT" to go back)
User clicks to put cursor on "Bootmark name" to show the keyboard
User types
User bookmarks by + button
User hides the keyboard by hitting back button,
User taps "ABORT" to get back to library

-------------------------
UX Case 2
User just taps + button to bookmark without typing, UX would flow like below

Tablet (Keyboard showing up automatically) - 4 steps
User taps bookmark button
User taps + button
User hides the keyboard by hitting back button
User taps "ABORT" to get back to library

Phone (Keyboard not showing up automatically) - 3 steps
User taps bookmark button
User taps + button
User taps "ABORT" to get back to library

-------------------------
Suggestion

(1) Keyboard tends to show up at the bottom of the screen hiding "ABORT" button to go back.
"ABORT" button could be turned to "x" button on the top-right corner to sidestep this issue.

(2) Or, to be more radical, + button could also act as "ABORT" button. User taps + button, it automatically goes back to library.

-------------------------
Caveats of Suggestion

For the simplicity, (2) would eliminate more steps than (1). Though it robs user choices.

(1) might change the consistent UX throughout the app ( "x button" never appeared in the app, though user is familiar with the concept of "x button" on the top-right corner, as that is the default UI of all Microsoft Windows and Android.

Sorry for wall of text.

ps. Is there any peculiar reason to user the term "ABORT" in all capital letters?
"Cancel" is familiar term to use iMHO. 
Whenever I see "ABORT" I feel like I'm in a falling spaceship with HAL9000 screaming "ABORT!!! ABORT!!!!" It scares me... ;-)

**Comment by Ph1b** [comment]
Thanks for the feedback, very useful. (especially the last sencentce made me laugh ^^ )

Some changes to make this more round:
* Click on the tick on keyboard adds the book immediately: 89231df4a552ba76965f85790b0d57fb32f3f31c
* Autocorrect and autocap: 65383186d8c4c4f2be79160876ba3e1b26d9be52
* Allowing bookmarks with the same time to be added, dont check for existing bookmarks (maybe you want to have more notes) and direclty closing the dialog after adding (with confirmation toast): fbbccae96e3971bef600f659a655a13f5c7ef71e
* Cancel instead of abort: db020f1d70cad34241360f1d4e738d9fbd4b6d35
* Prevent keyboard to show on start: 0ef78715371a009bed1e82c7538e593c00e84d5d
