### ISSUE TITLE
1.5.4-rc1 // Widget & Player Playbutton Sync not

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#126]
User taps widget to play music
User goes into playback screen
Play button is still ">" not "||" which is what widget & notification bar shows.
User taps play button once or twice, it now in sync with other widgets.

logfile
https://gist.githubusercontent.com/JoshGraham/c872a52c1ecdb9802842/raw/c2fa532585c094c4f4614d779207cd283ea6691e/gistfile1.txt

**Comment by Ph1b** [comment]
Should be fixed in 1.5.4rc2: https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/v1.5.4-rc2
