### ISSUE TITLE
Support for seek buttons on Bluetooth headset

### ISSUE THREAD

**Issue by dandv** [Ph1b/MaterialAudiobookPlayer#128]
I have an LG 730 Bluetooth headset that can be used to control playback. The pause and prev/next track work, but long press on the prev/next buttons doesn't do anything. In other apps, e.g. Music, it seeks backward/forward.

Very useful when listening to audio books while driving, instead of fumbling with the phone.

**Comment by Ph1b** [comment]
Does this work with the the latest rc? https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/v1.5.4-rc2

**Comment by ministryofsillywalks** [comment]
latest rc (1.5.4.-rc2) works with my pebble smartwatch (also BT)

**Comment by Lawpoint** [comment]
I installed the app about 3 weeks ago (don't remember the version) and it worked great out of the box - BT seek buttons worked as intended. However, after the recent update (1.5.4.2) BT seek buttons began to skip entire track instead of jumping 20 seconds through it.

**Comment by Ph1b** [comment]
Please reopen and report if this is still the case in the latest nightly.

**Comment by dandv** [comment]
In v2.1.9.1, the "seek to previous/next song" action seeks back/forward by the set amount of seconds, but the "seek within track" action doesn't do anything. I use an LG HBS-900 headset. A single "flick" of the seek button seeks to the next track in other apps (e.g. stock Music app, Podcast Addict, Vanilla), and a long flick seeks within the track. In MAP, the long flick does nothing, and the short flick seeks within the track.

I personally like this, because my audiobooks are long files and I only want to seek within them, but the behavior might deviate from what most other apps do.
