### ISSUE TITLE
1.5.4-rc2 // "Album-art" part of widget behavior

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#132]
Tapping "Album-art" part of widget behavior
--------------
Expected behavior
1) Tapping "Album-art"  
2)- goes to 
Playback screen 
3) Tapping back button 
4)- goes to 
Bookshelf screen
---------------
Issue
First time, it succeeds.
The times after,  after step 3) - goes to 
Home Screen
----------------
ps. this behavior was already present at 1.5.4-rc1

https://gist.githubusercontent.com/JoshGraham/b5205c13e7e912dd604c/raw/b7ab959f64e7f4bc64c65627ec999eec75027ba9/gistfile1.txt

**Comment by Ph1b** [comment]
Fixed as of e719ea68534af2249ee870ac79268a999a4d5824
