### ISSUE TITLE
1.5.4-rc2 // UX suggestion : Importing folder

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#133]
I'm not sure I've made this ticket before,
if I did, please close it.

---------------------------

Now, after importing a folder - it goes back to library screen.
If I'm importing several folders - I have to navigate to that place - everytime I import another.
Redundant tapping - Repeats of same beahvior several times.

Wouldn't it be better,
after importing a folder - it stays at the exact point at folder structure, thus imports other albums.
Then, if user wants to go back to library, one taps on back button.

-----------------------------

I remember I've made similiar suggestion of letting user choose the "default folder" and closed it because unnecessary complication of codes, when importing process is far and between-not happening daily.

But maybe by making screen stay and that folder structure when doing importing
without making user navigate to that exact folder everytime user wants to import something,
one can have benefit of not doing same navigating over and over without making "default folder" setting.

---------------------------------

Josh

**Comment by Ph1b** [comment]
Problem solved as of https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly-1503180418 ;-)
