### ISSUE TITLE
File info lost after update

### ISSUE THREAD

**Issue by daisywreath** [Ph1b/MaterialAudiobookPlayer#135]
I just updated to v1.5.4.2, and afterward the app seemed to have lost the file info for the book I was listening to. It still showed up in the library, but when I opened it, the book length was listed as 0:00:00. I also lost the icon on my home screen and had to re-add it from the app drawer. (Seems to be behaving as though I uninstalled/reinstalled, but I'm 100% sure I only updated it.) Is there any way to export data before an update, maybe? Not sure if it would make any difference, but the file is stored on external SD card.

**Comment by Yma981** [comment]
Same here, but in my case the files were stored in the internal SD

**Comment by Ph1b** [comment]
Should be of no value as of https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly-1503180418
