### ISSUE TITLE
material player will not play files

### ISSUE THREAD

**Issue by OdinVon** [Ph1b/MaterialAudiobookPlayer#136]
Material Player Version 1.5.4.2
Samsung Galaxy Note 4
Book files on Sandisk 128 GB SD 

I can open the player, but when I select a title or file and press the play button nothing happens. No audio starts. The play icon doesn't change to the pause icon. The timeline stays at 0.

I hade restarted the phone and still the same results.

The app did not work until I uninstalled and reinstalled it.

**Comment by Ph1b** [comment]
Thanks for the report. Should work as intended as of https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly-1503180418
If not, please open a new ticket.
