### ISSUE TITLE
Play/pause on headset button

### ISSUE THREAD

**Issue by deniss-s** [Ph1b/MaterialAudiobookPlayer#137]
Would be very convenient to have pause/resume when headset's button is pressed (like other audio players).

**Comment by rvowles** [comment]
does the setting in the preferences no longer work? I saw this this morning.

**Comment by deniss-s** [comment]
I don't know which preference is responsible for the headset button. I have checked the behavior once once again - MaterialPlayer ignores the button, however the default music player (Apollo) pauses and resumes playback when button pressed.

**Comment by Ph1b** [comment]
Does this work in latest nightly? https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly-1503180418

**Comment by deniss-s** [comment]
This version does not show any audio files... I add folder, but the list remains empty. So cannot check if headset works.

**Comment by Ph1b** [comment]
Thats weird. Please open a new ticket with how your folder structure looks and which folder you imported.

**Comment by deniss-s** [comment]
New version does not work correctly with cyrillic folders (https://github.com/Ph1b/MaterialAudiobookPlayer/issues/153), however the button works now. :)
