### ISSUE TITLE
Home wall widget doesn't show the book cover

### ISSUE THREAD

**Issue by Yma981** [Ph1b/MaterialAudiobookPlayer#138]
I dont know if it is meant this way but the home wall widget doesn't show the book cover after playing a file. The lockscreen widget shows the book cover normally.
The previous versions used to show the book cover on the wallscreen widget. 

current version: 1.5.4.2
Android 5.0.2 Resurection Remix

**Comment by M3tthew** [comment]
same problem

**Comment by JoshGraham** [comment]
nightly-1503180418
it seems like 4x1 has no book cover
In tablet, 5x1, 6x1... shows book cover

**Comment by Yma981** [comment]
nightly-1503180418
4x1 Wall Widget Still doesn't show the book Cover

**Comment by Ph1b** [comment]
Thanks for the reports.

Can you pls check if it works in the [latest nightly](https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly15-03-23-00-14) like shown [here](https://www.youtube.com/watch?v=UOGIE6XqX10)?

**Comment by JoshGraham** [comment]
nightly15-03-23-00-14
shows bookcover from 3x1 to higher
seems fixed
