### ISSUE TITLE
Player auto-starts when Hangout message or Alarm goes off

### ISSUE THREAD

**Issue by rvowles** [Ph1b/MaterialAudiobookPlayer#139]
With the latest update, the player is now unusable as it starts playing automatically whenever I get an SMS, Hangout message or when my calendar entries go off.

**Comment by ministryofsillywalks** [comment]
also have this issue in 1.5.4 rc2
just about everything i do starts the player again.
calling someone and then hanging up for example.
I even dismissed the notification after i paused the current track and it still unpauses with a lot of events.

**Comment by Lawpoint** [comment]
I'm having exactly the same issue (1.5.4.2, Nexus 4, 5.0.1)

**Comment by Yma981** [comment]
Me too except when i receive whatsApp messages ....

**Comment by M3tthew** [comment]
same thing with viber.

**Comment by Ph1b** [comment]
Should be fixed as of [nightly-1503180418](https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly-1503180418). If not, please re-open.
