### ISSUE TITLE
1.5.4-rc2 Bluetooth FF/REW buttons skip files instead of +/- 20 seconds

### ISSUE THREAD

**Issue by innesst** [Ph1b/MaterialAudiobookPlayer#141]
1.5.4-rc1 and 1.5.3 work as intended.

**Comment by Ph1b** [comment]
Does this work in latest nightly? https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly-1503180418

**Comment by innesst** [comment]
Seems to work fine now. Tried it on a couple of files.
Thanks!
