### ISSUE TITLE
Link to Google play is dead

### ISSUE THREAD

**Issue by jsiei97** [Ph1b/MaterialAudiobookPlayer#142]
Hi

It seems like your app is removed from Google play, or the link is broken.
Are you aware of the problem?

Note: App is still available on F-Droid so it is still reachable for the masses.

BR
Johan

**Comment by Ph1b** [comment]
I am aware of the problem. I took it off the market after changing too much and letting some bugs slip in. I took a lot of time and rewrote large parts. If this seems stable, I'll re-release it.
If you have time for testing, that would be great, thanks.

(nightly-1503180418)[https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly-1503180418]
