### ISSUE TITLE
How to remove an audiobook from the library?

### ISSUE THREAD

**Issue by jans23** [Ph1b/MaterialAudiobookPlayer#144]
The title says it all. I really tried but couldn't figure it out. Hope this can be solved easily?

**Comment by Yma981** [comment]
In the MAP main view, choose the book you want to remove on the lower right of its book cover you can find three vertical dots, press those a dropdown menu will appear telling you:
Edit
Delete (press this one)

**Comment by jans23** [comment]
This solves it. I don't know why I didn't recognized the dots in the 
first place... Anyway, thanks for your help.
