### ISSUE TITLE
Sometimes menu under settings is to big

### ISSUE THREAD

**Issue by asd-and-Rizzo** [Ph1b/MaterialAudiobookPlayer#147]
Happens randomly on Samsung Galaxy S5 Anroid 5.0

![screenshot_2015-03-10-16-42-25 1](https://cloud.githubusercontent.com/assets/757125/6575974/96b67fdc-c744-11e4-89f1-921422d3785e.png)

But sometimes it good
![screenshot_2015-03-10-17-49-54 1](https://cloud.githubusercontent.com/assets/757125/6577399/d0efe0b2-c74e-11e4-9ccb-baee43a9e343.png)

Not sure whom to blame.

**Comment by Ph1b** [comment]
Thx. Should be fixed as of https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly-1503180418
