### ISSUE TITLE
nightly-1503180418 // First Impressions + one possible bug?

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#148]
## Disclaimer
1. I've let lollipop update pass me by, I'm still in Kitkat. I still don't get Material-Design. So, take everything in grain of salt.
2. Design-taste (UI/UX) differs from person to person. Only developer knows what developer needs to do. Developer should say 'no' to tester's weird taste. ;) 

## Impressions

1. 
~~Dark theme
In lollipop, everything is white in background.
It hurts my eyes. Really bad.~~
EDIT : fixed in nightly15-03-23-00-14

2. 
Pop-ups, necessary evil
Nobody likes pop-ups. I just click 'yes' to whatever pops up. Go away pop-up, whatever you are. Delete everything? Yes. Please.
I see why pop-ups are needed in this version; '+' button to import folder is replaced to 'audiobook folder' in settings. User needs education.
Still, pop-ups are still horrible. What could be better...I'm not sure.

2-1 
audiobook folder in settings (maybe bug)
If user choose audiobook folder, which includes lots of audiobooks : It just works. Everybook is imported.
If user(i'm so confused) choose 'every audiobook seperately'. This happens.

![0](https://cloud.githubusercontent.com/assets/8502832/6703858/b5402f0c-cd84-11e4-941c-2d7705c0acc2.png)

I still pray users do as they are told to do. Unfortunately, not really.
So, I'm not sure this is a bug, or user's a bug; as they don't do what they're meant to do. ;) Or, it could be UI/UX matter, as user is confused whether to choose 1)folder which contains lots of audiobooks or 2)every audiobook folder seperately.
Most users would follow 1), at least I hope so.

----------------
~~3~~
~~Notification-widget // Homescreen-widget~~
    <<  ||   X         //      <<  ||  >>
~~I tapped 'X' at notification, thinking it was '>>', because Homescreen-widget is that way.
I'm stupid and confused user, so it'll not happen to other users. And I see why their functions are different.~~
So, non-issue.

------------------
~~4
Unconhesiveness of 'NO'-'OK'
Playback Speed : CANCEL / SET
Audiobook Import : ABORT / CHOOSE
Audiobook Delete : KEEP / DELETE~~
EDIT : fixed in nightly15-03-23-00-14

4-1
It's just personal taste, but their colors and sizes are not cohesive throught out app.
Again, it's (stupid) Lollipop-design-principle in the first place. I just can't fault anyone design-wise.

~~4-2
CANCCEL SET ABORT CHOOSE KEEP DELETE
Oh, yeah pop-ups. What should I click to make this go away?
Sorry, pop-up makes me stupid than usual
I'm so stupid I just need Cancel or OK.~~
EDIT : fixed in nightly15-03-23-00-14

~~4-3
Capital letters scare the crap out of me. I don't know why.~~

--------

Conclusion
I'm stupid. I don't get Lollipop. Pop-ups make me more stupid. Capital letters make me scared.

Please take all of these with grain of salt.
You should say 'no' to stupid users like me :)

Josh

**Comment by JoshGraham** [comment]
Oh, now I get it.
It's not importing, it's 'syncing'.
No wonder I couldn't get what it was meaning to do. I could never get used to Itunes Syncing, I just keep deleting itunes songs :)
Quite interesting. I see how it's more efficient than the concept of 'importing every folder over and over' -'deleting individual albums over and over' ;Just sync to the correct audiobook folder and forget the rest. Cool.
I hope other users get it sooner than I do. :)

**Comment by JoshGraham** [comment]
Sorry for all the 'stupid' words on the first impression
Linuz has gotten to my tongue, I guess.- https://www.youtube.com/watch?v=4XpnKHJAok8
---

I think I finally figured out why I was so irritated at first impression.
When I thought I knew how it works, then it doesn't. I get irritated and stupid, so I hate it.
The thing is, buttons and flow totally changed in this nightly, compared to others version before.
1.
Pop-ups, Pop-up in Pop-up.
![3](https://cloud.githubusercontent.com/assets/8502832/6708337/b6df4d24-cdb2-11e4-9de1-74b579dc4bb4.png)

2.
+ button was upper-right, now it's down-right.
3.
It's not importing folder anymore, it's syncing.
You don't individually edit folders anymore, let the folder sync!

It's user's problem that is,
User favors familiarity over better, new way of doing things.
Maybe it was just me, but it was that. ;)

Josh

**Comment by JoshGraham** [comment]
Alternative terms for "NO-OK'

Playback Speed : CANCEL / SET
That's fine
Audiobook Import : ABORT / CHOOSE
                         into  Cancel / Set
Audiobook Delete : KEEP / DELETE
                         into  Canel / Remove

I always look for 'cancel' when in unfamiliar pop-ups,
And I don't want to 'delete' anything by mistake, 'remove' is much better, it sounds like 'it's just being placed somewhere else, I could get it back anytime I want to.'

**Comment by Ph1b** [comment]
Thanks for all the feedback. As you can see I read it and implemented some things.

# Ui Consistency
What do you suggest? You can just write, I would here there and there replace this and this with that.
# Dialog buttons
Yeah, that was confusing. Fixed now.
# AutoImport
That is something  users will have to go trough. Sure its confusing if you come from the old version, but there are ideas in my head, so progress has to be made ;-)
# Dialogs
There are [fullscreen dialogs](http://www.google.com/design/spec/components/dialogs.html#dialogs-confirmation-dialogs). We could implement them for some fields. Where do you think that makes sense? What mostly annoys me is the floating actionbutton in a dialog which opens another menu.
For the confirmations: Sure you dont like them but people press things accidentially so I dont want to have all gone by mistake, especially on removing actions.
# Design overall
Ok, but you took a screenshot with all the colors available. I mostly leave the player in dark mode, its kind of calming. You can make color suggestions:
[Palette](http://www.google.com/design/spec/style/color.html#color-color-palette)
[Current colors](https://github.com/Ph1b/MaterialAudiobookPlayer/blob/master/audiobook/src/main/res/values/colors.xml)
[Resolve html colors](http://www.colorpicker.com/) #ff37474f without alpha is 37474f

**Comment by JoshGraham** [comment]
Thanks for reply.
UI and color-wise, It'd better if I don't touch it, as more I dabble less functional it gets.

I just accept applications as 'If it is good enough for daily use, it's fine."
As a user, familiarity, stabilty and realibility triumps over any progress of functionality.

Though on the top of my hat, some underlying principles
1) Less pop-ups, better
2) Less taps, better
3) Less chance of user screw-ups, better
4) Undo as unintrusive as possible, user redeems itself from screw-ups fast

Having said all that, it reads like Apple philosophy :-/
Again, I don't really 'get' design. :)

Again, things are just fine as it is to me, as long it's core functionality is sane.; 'My control over audiobooks as I see fit'

Thanks
Josh
