### ISSUE TITLE
Can not Remove Audiobooks from List Anymore (nightly-1503180418)

### ISSUE THREAD

**Issue by Yma981** [Ph1b/MaterialAudiobookPlayer#150]
On nightly-1503180418

After Choosing the Audiobook Folder, After it is populated with Audiobooks: We can NOT remove book from the list, Only Audiobook Name and Cover Editing is Allowed.

**Comment by Ph1b** [comment]
That is by design. You just show your library. Removing books there would be confusing. Just move them from your audiobook folder. Otherwise we would need a list of hidden books in case people want them back.
