### ISSUE TITLE
Ignores folders with cyrillic paths

### ISSUE THREAD

**Issue by deniss-s** [Ph1b/MaterialAudiobookPlayer#153]
Latest nightly https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly-1503180418 ignores folders with cyrillys (probably other unicode symbols in path).

**Comment by Ph1b** [comment]
Can you please describe what you mean by that?

Are the folders choosable and the books are just not being fetched? Or dont you see the folders?

**Comment by deniss-s** [comment]
I've played around with file names and figured out that all my audio files with capitalized extensions are ignored. Thus, unicode symbols are not the problem.

In my particular situation all files ending with *.MP3* instead of *.mp3* are not visible. :)

**Comment by Ph1b** [comment]
Should be fixed as of 9cc4bd270f3eabeebf0eedd90e827f3b4627c72a

Please test and report if not so [nightly](https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly15-03-19-16-31)
