### ISSUE TITLE
nightly15-03-19-16-31 - Dark Theme

### ISSUE THREAD

**Issue by innesst** [Ph1b/MaterialAudiobookPlayer#154]
You did say nitpick, right ;) 
I do not like the color of the play button or sider (too pink), and the 3D effect of the play button hurts my eyes. Love the recent improvements!

**Comment by JoshGraham** [comment]
Oh, my. I love hot pink. ;)
If we could choose the colors, it would be nice.
But that's making things pretty, so I'm not sure how high priority that would be.
Probably not much... :)

**Comment by Ph1b** [comment]
If you have any colorsuggestions. post them.
You can find colors with ##ff... code [here](http://www.google.com/design/spec/style/color.html#color-color-palette).
I won't implement a color picker since that's overload.
