### ISSUE TITLE
nightly15-03-23-00-14 // lots of data

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#155]
Is it side-effect of syncing?
Would this data just keep going up?
![0](https://cloud.githubusercontent.com/assets/8502832/6774205/76f97bec-d160-11e4-8412-efd1f248e41c.png)

**Comment by JoshGraham** [comment]
issue present since
nightly-1503180418

**Comment by JoshGraham** [comment]
Not reproducible. User misconfiguration. Closed

**Comment by Ph1b** [comment]
This was no user misconfiguration, this was a bug present in the previous nightlys.
