### ISSUE TITLE
nightly15-03-23-00-14 // Force crash at open

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#156]
nightly15-03-23-00-14
Not sure if misconfiguration.

---

* Description of problem:
After fresh install, tap to open.
Force crash.
Pop up says : There's no app to send mail
Second try, everything's working fine.

* Actual results:
Force crash. Pop up says : There's no app to send mail
* Expected results:
Open app

--

logfile
https://gist.githubusercontent.com/JoshGraham/4125740229e3458e6abe/raw/356d4dc0b05cb173fb7dfc93247066590bad4cc6/gistfile1.txt

**Comment by rthorp** [comment]
I had exactly the same issue with the nightly15-03-19 build, but the nightly15-03-23 build works fine for me. Strange.

**Comment by JoshGraham** [comment]
At nightly15-03-23-00-14
On Nexus 7(tablet), it's fixed.
On MotoG (phone), it crashed.

Not sure, my devices aren't clean state (heavily modified).
Confusing to me as it's app's fault or my device's.

**Comment by Ph1b** [comment]
Is this still present in [2.0 RC1](https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/v2.0-rc1)? Is that present every time? Is the app completely unusable on these devices? What happens if you remove the widget?

**Comment by JoshGraham** [comment]
Referenced at #158

**Comment by Ph1b** [comment]
I didnt get it. 

1. Is it still present? 
2. Is there no mail popping up? 
3. And do you mean with fresh install not clearing data, rather uninstalling and then installing again?

I cant see any suspicious in the logfile. Im just wondering about the BaseWidgetProvider:
```03-24 22:03:51.485 I/ActivityManager( 1076): Start proc de.ph1b.audiobook.debug for broadcast de.ph1b.audiobook.debug/de.ph1b.audiobook.receiver.BaseWidgetProvider: pid=26510 uid=10168 gids={50168, 1028, 1015, 3003}```
Why is the widget called when this is a fresh install...

**Comment by JoshGraham** [comment]
Aw, it wasn't clean install, my bad.

-v2.0-rc2
1. It seems fixed.
2. No crash, so nothing.
3. Again, dirty install, my bad.

Seems fixed.

**Comment by JoshGraham** [comment]
- v2.0-rc2
Maybe app sees itself as dirty install, if user wipes app's data to start afresh.
So, even if data's gone, if there's a widget, app crashes.
Not sure it's bug, or misconfiguration
Close again, if it ain't bug.

- The process to reproduce the crash
1. At settings, force stop app. Clear app's data. Open app by widget.
2. Three consecutive crash pop-ups. 'Sending MAP Bugreport..' pop-up behind crash pop-ups.
3. Then, app works fine after importing folders.
3-1. If chooses not import folders, and goes back to widget to open app once again. Go to 2

logfile
https://gist.githubusercontent.com/JoshGraham/697c09a758c0e97426b6/raw/a52daeb16041f528f8e929045814c1ff0b890766/gistfile1.txt

Thanks
Josh

**Comment by JoshGraham** [comment]
- Screenshot
[1] BugReport pop-up behind crash pop-up, three times.
[2] If user doesn't tap anything, it starts app just fine.

[1]
![1](https://cloud.githubusercontent.com/assets/8502832/6942199/e362faa8-d8c0-11e4-9459-3ab8cabd7265.png)

[2]
![2](https://cloud.githubusercontent.com/assets/8502832/6942204/e9f1c3a4-d8c0-11e4-9b1e-9711816417ae.png)

**Comment by JoshGraham** [comment]
fixed at v2.0.3
