### ISSUE TITLE
Issues with nightly15-03-23 build

### ISSUE THREAD

**Issue by rthorp** [Ph1b/MaterialAudiobookPlayer#157]
I have a couple of issues (may have been in all builds but noticed them in this one).

1. After exiting the app, and there is an entry in the Notifications pull down window (for the last book that was being played), and it is **not** the only Notification entry, then the Rewind, Play and Stop functions do nothing when pressed (apart from quickly being highlighted so that you know you actually touched them). Touching the name of the book always reopens the app as expected.
When the MAP notification is the only one displayed, then Rewind/Play/Stop work as expected. 
On my tablet I have a calendar notification in the pull down (ie an all day event), so not sure where the problem is (my tablet, calendar software or MAP).

2. This is a minor issue as I wouldn't expect the following sequence of actions to be done very often :).
When a book consists of multiple audio files in a folder, perform the following:
  * select book from main screen
  * start book playing
  * press the 'skip file' icon (>|) numerous times ie to keep skipping files. After a number of skips - sometimes 5, sometimes 10 or more, the application 'freezes' for that book ie it stops playing audio and none of the buttons work (ie |< << || >> >|).
The 'back' softkey works to go back to the main screen, but touching any other book icon then seems to freeze the app and after 30 secs or so you get the  'application has stopped working' popup.

Richard.

**Comment by Ph1b** [comment]
# Notification Issue
I cannot confirm the first issue. For me the notification always works, no matter how many notifications are there. Is someone else facing this issue?
# App freezing
As of the nightly I will release this evening this should be fixed. Please report if not so.
