### ISSUE TITLE
v2.0-rc1 // First impressions

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#158]
##### "Are you loading or lagging? Give me something!"
After setting the default audiobook folder, user is presented with no feedback of "things are happening!" 
If files are large and big, it need some time to load them all up to the screen.
Some kind of messege eg. "Wait a sec...for whole books to load" would be fine.

##### "Want to feedback?" "Want to feedback?" "Want to feedback?"
bug #156 is present.
But, IIRC not when it opens, but when it crashes.
Thing is, pop-up of 'send mail' also disappears without user choosing any action.
~~"User gets confused of what the -- just happened, still doesn't understand and hit the app again. It works fine now. What a spooky thing that was, whatever."~~EDIT:misunderstanding

Maybe feedback could be impeleted to either as, or both of
  - As Firefox does its force-crash reporting. Asking user gracefully to send its bug report - Giving user choices though if repeated crash, user gets irritated as hell
  - New setting checkbox - Opt-in/Opt-out - "Give developer bugs report for app quality?" - Check once, don't bug me with pop-ups again.

##### Magical syncing depends on user's folder structure and user behavior
How does this app recognize which are the 'audiobooks' and which is an 'audiobook'?
There are several experiences of syncing - possible scenarios of what would actually happen.

- Succesful case
Tree structure- Import mother folder - Success

- Other cases
Structure - User behavior - Various fail results

eg 1. Tree structure - Import mother-folder - Success!
Mother-folder(import)
 | child-book 1
 | child-book 2
 | child-book 3

eg 2. Tree structure - Import child-folders - Fail! - Every songs are folders
Mother-folder
 | child-book 1(import) 
 | child-book 2(import)
 | child-book 3 (import)
![0](https://cloud.githubusercontent.com/assets/8502832/6884248/1134cd40-d622-11e4-846f-bb789798e699.png)

eg 3. Tree-in-tree structure - Import mother-folder - Fail! - Different books are all seen as 'A book"
Mother-folder (import)
 | child-folder 1
 || grand-child-book 1
 || grand-child-book 2

 | child-folder 2
 || grand-child book 3
 || grand-child book 4

grand-child-book 1 & 2 will be seens as child-book 1
grand-child-book 3 & 4 will be seens as child-book 2

eg 4. The variants of case 1 & 2 - Various user experiences of Fail!

-
If the app can't successfully recognize 'One Folder = One Audiobook'. 
Syncing audiobooks would let users with different experiences.
Some say "It just works!"
Other say "What the -- is it trying to do?"

Thanks
Josh

EDIT: Syntax. Markdown is hard.

**Comment by JoshGraham** [comment]
- Another idea of feedback using Google Play Market Feedback agent. Asking after reopening app after crash. For example, [Chatsecure] (https://github.com/guardianproject/ChatSecureAndroid)

![0](https://cloud.githubusercontent.com/assets/8502832/6890913/1afb8b16-d6ef-11e4-9726-3e548905715c.png)

**Comment by Ph1b** [comment]
I implemented a progressbar in the latest nightly and a short explanation.

About the bug reports: Thats way way way too much efford for what we want to archieve. You cannot use the play crash reporting mechanism when in debug mode (not released) and I dont mind that. If testers find an error, this is the easiest way to get the crash.
