### ISSUE TITLE
Green distorted Album covers

### ISSUE THREAD

**Issue by Yma981** [Ph1b/MaterialAudiobookPlayer#159]
in map-2.0-rc2-debug.apk

![screenshot_2015-03-31-11-01-18 1](https://cloud.githubusercontent.com/assets/10189895/6914879/f80b90c0-d797-11e4-8f9d-63f104f16479.png)

**Comment by Ph1b** [comment]
Is this always the case?

**Comment by Yma981** [comment]
No, I had a previous nightly, it was ok then it turned green.

I uninstalled the previous nightly and just installed the RC2 (i didn't delete MAP data, just uninstalled it) and the problem persisted.

**Comment by Ph1b** [comment]
[quote]Is this everywhere you can see the cover?[/quote]

**Comment by Yma981** [comment]
yes Everywhere, 
Widget, inside Audiobook window, main window(Main directory)

**Comment by Yma981** [comment]
I deleted the App Data and Cache and reassigned the Audiobook Folder.... The problem persisted

**Comment by Ph1b** [comment]
And after reboot?

**Comment by Yma981** [comment]
the Problem remained after deleting cache/ App Data and Rebooting

**Comment by Ph1b** [comment]
Please check  the files in a book directory (starting with a dot(normally hidden), then folder name, then -map.jpg, with a normal image viewer. Are the greenis there too?
".HarryPotter.map-jpg."

**Comment by Yma981** [comment]
I checked the hidden images inside every Audiobook Folder with the standard image viewer.
 YES they are all GREEN and distorted

**Comment by Yma981** [comment]
I deleted the .json and the hidden images, bookmarks and all files made by MAP. Everything returned to normal.

Thanks a lot

**Comment by Ph1b** [comment]
If someone faces this issue, pls reopen!
