### ISSUE TITLE
Changelog is out of date

### ISSUE THREAD

**Issue by deoren** [Ph1b/MaterialAudiobookPlayer#161]
Hi,

I noticed on F-Droid that there was a new 2.0.4 build. I came here to review the changelog and found that it last shows details for for v1.5.4.

I've used it to listen to a few books now and have enjoyed it thus far. Thanks for your work!

**Comment by Ph1b** [comment]
Done as of 1f198759b302838e4ffa85b8b1e86d757f305a6d, thanks.
