### ISSUE TITLE
Bug: Skipping doesn't work on Samsung S4mini with CM12 

### ISSUE THREAD

**Issue by MarvAmBass** [Ph1b/MaterialAudiobookPlayer#163]
Hey there, I have troubles with CM12 and your Player. Unfortunatly I cannot say if this bug exists on other devices.

If I press any of those two skip buttons besides the Play Button - nothing will happen - not even in the logs.

I only scan skip parts by using the slider which is annonying because it's hard to hit the right places with your finger.

Do you have any idea why this buttons are dead on my devices?

Thank you

**Comment by Ph1b** [comment]
Which version are you using? Do they react? (give visual feedback). Is it for all books that way?

**Comment by MarvAmBass** [comment]
I'm using 2.0.5 from f-droid.org - got this bug since I started using your Player (about 2 Months from now)

Buttons give visual feedback - but no skipping is done.

I'm listening to mp3s about 600MB and 4-5 Hours long.

I tried to listen to a shorter mp3 (a 5MB 3 Minute Song) here it worked like a charm.

I'll try a converted version of my 600MB file (wav) - but it takes some time to get on the phone ;)

I'll keep you updated

**Comment by Ph1b** [comment]
Is the length and position besides the seekbar displayed correctly?

**Comment by MarvAmBass** [comment]
okay just checked the 3GB Wav file. Same Problem as with the 600MB mp3.

Yeah Length and Position is displayed correctly.

but i'm still only able to skip the small 5MB mp3

**Comment by MarvAmBass** [comment]
just did some adittional checks, I now converted the working small mp3 to wav and back to mp3 with the same encoder I've used to convert my huge mp3.

the new small mp3 and wav works like the original one before

**Comment by Ph1b** [comment]
Fixed as of b8b0e6fb5651ad5100d00a64dc073915280ab09f

Returned wrong duration, (10^3 too large), so cast to int caused int to swap. Because of that, big files were redirected to a next() which was ignored in this case since there is just one file.

**Comment by MarvAmBass** [comment]
wow that was fast! Thank you very much!

**Comment by MarvAmBass** [comment]
Thanks it works perfectly now

Great app thx
