### ISSUE TITLE
Feature request: Chromecast/Google Cast

### ISSUE THREAD

**Issue by steffenbb** [Ph1b/MaterialAudiobookPlayer#165]
Sometimes when you're just walking around in your room, or laying in your bed and find the headset plugged in quite a bit enjoying it would be nice to be able to stream the audio book through this great app to a TV or a google cast compatible device. I often use Bluetooth to gain this connection to my speaker. But it isn't as easy as using Chromecast forexample as I am surrounded by those no matter where I am in my house.

**Comment by Ph1b** [comment]
This is quite low priority since I dont think many people have this, including me. But if anyone wants to write support for it, I'll support it!
