### ISSUE TITLE
headset button steals focus from other players

### ISSUE THREAD

**Issue by rattkin** [Ph1b/MaterialAudiobookPlayer#166]
example: 
1) open MaterialAudiobookPlayer and exit with back button or home button, do not start playback
2) run another music player and start playback there (antennapod for example)
3) press headset button. MaterialAudiobookPlayer starts playback

how do i prevent MaterialAudiobookPlayer from recieving headset button events, when another player is running?

**Comment by Ph1b** [comment]
Thanks for reporting.
Should be fixed as of d7c899dea169ef260eef484e8789cef3b77fff26 and included in the latest release. Please reopen if problem still occurs.
