### ISSUE TITLE
Application hangs if the files of a loaded book have been removed externally

### ISSUE THREAD

**Issue by major-laslo** [Ph1b/MaterialAudiobookPlayer#168]
If I delete a book in a file manager, that was loaded in the app (current version from the Play Store), the application hangs on startup every time, even after removing it from recents to force a restart. 

Only workaround for it as a user has been to delete application data.

Encountered on: Nexus 5, Lollipop 5.1, app version 2.1.2.1
I have also submitted several crash reports with similar titles if that information helps.

**Comment by Ph1b** [comment]
Cant con firm this. Also I cannot see any crash anyhwere. Can you say what the exact steps are?
You can find the previous releases here:
https://github.com/Ph1b/MaterialAudiobookPlayer/releases
Thanks, Paul

What do you mean with hangs? Does it really hang = do nothing? Or does it just crash?

**Comment by major-laslo** [comment]
It produced an ANR without managing to fully load the app. Could be important - I always open the player via its widget. So the steps for me are:

Have book loaded and paused -> exit app (and dismiss from notifications) -> delete directory of the book (not the parent, just the book) -> click widget (which still shows the book loaded) -> application gets stuck on launch and shows ANR in a couple of seconds.

I'll provide more details tonight, and if you can not reproduce it, I'll try to compile and run on my system to take a look at debug info.

**Comment by Ph1b** [comment]
Can you still reproduce this in the [latest release](https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/v2.1.3)?
If so, please reopen!

**Comment by major-laslo** [comment]
Can't reproduce any longer with the new build, cool. It gets a bit weird, with the player still being able to resume a file that has been 'deleted', but then the book disappears when going to the book folder activity.

Thanks for the awesome app, and sorry I wasted your time with an outdated issue!

**Comment by Ph1b** [comment]
Thanks. That was not wasted, it was a threading issue I fixed. Please report anything you find.
