### ISSUE TITLE
BIG play/pause button

### ISSUE THREAD

**Issue by Ridderby** [Ph1b/MaterialAudiobookPlayer#169]
Hi, 

I have been using audio books a lot and listening to audio books differs from music as you would not like to miss a second of the book. So when distracted by something you like to hit the pause button and nothing else. 

In many cases you may be in bed, or in the car or so it would help if the play/pause button is huge, more or less the entire screen. Therefore I suggest using the cover art as an play/pause button as this part takes the most of the screen. 

I have done so myself when I developed a player in Qt for Nokia N9 and Jolla and it is really helpful when the traffic-info takes over during driving and you are in a hurry to pause the book. 

BR
Erik

**Comment by Ph1b** [comment]
Implemented as of 113ea9c458c4c67e310410109f400c6d2fa9fce6

**Comment by Ridderby** [comment]
THANKS!
