### ISSUE TITLE
suggestion // Edit Book : maybe more than book cover editing

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#174]
Now, 'Edit Book' launches to edit cover-art.
That's find and good, though.
Maybe it could bring up Bookmarks with/without cover-art?
Editing Bookmarks in Library screen, rather than just in Playback screen, might allow more interaction with bookmarks
One may like to access bookmarks in Library screen, rather than going to Playback screen, just to view what they've marked.
Just thoughts.

**Comment by Ph1b** [comment]
Implemented as of 190a2f55ba2b9de77ca992cc19e8419be84f7f1b
