### ISSUE TITLE
Use cover art from file

### ISSUE THREAD

**Issue by lightonflux** [Ph1b/MaterialAudiobookPlayer#175]
MAP doesn't use jpg files for cover art.

In older collections you often have the cover art as a separate file with the exact same name as the audio, just with another extension (jpg/jpeg/png).

It would be nice if MAP would use these files automatically, if the audio file has no cover art in the metadata.

**Comment by Ph1b** [comment]
If there is no cover yet, the app actually [searches for jpg, jpeg, png and bmp files](https://github.com/Ph1b/MaterialAudiobookPlayer/blob/v2.1.5/audiobook/src/main/java/de/ph1b/audiobook/model/BookAdder.java#L179)
