### ISSUE TITLE
What happens with old json files?

### ISSUE THREAD

**Issue by lightonflux** [Ph1b/MaterialAudiobookPlayer#176]
If the user removes the audio files manually, but does not touch the old json files, will they be removed automatically some time later or just stay where they are?

If MAP doesn't do anything with them yet, is it planned to implement automatic removal or something else?

**Comment by Ph1b** [comment]
As of [2.1.2.1](https://github.com/Ph1b/MaterialAudiobookPlayer/tree/v2.1.2.1) the app does no longer write to sd card since there is a permission error. So these are leftovers which can be deleted manually and won't be regenerated.
