### ISSUE TITLE
2.1.5 // google play billing error

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#177]
Pop-up says "This version.. incompatible with Google Play Billing..."
Sounds like it shall be fixed when pushing app to Google Play.
Close, if so.

**Comment by Ph1b** [comment]
Do you use the version from google play store? At what point does that problem come? When I try it with my girlfriends device, it works fine (cant try it on my own device since I can't buy my own inapp purchases).

**Comment by JoshGraham** [comment]
Oh, my mistake. It was F-droid ver. 
What was I thinking..;)
Closed.

**Comment by Ph1b** [comment]
> Sounds like it shall be fixed when pushing app to Google Play.

To make sure there is no misunderstanding: [map on playStore](https://play.google.com/store/apps/details?id=de.ph1b.audiobook)

**Comment by JoshGraham** [comment]
Yup. Google Play version is no problem.
Of course, F-droid-signed apk won't support Google Billing Service. That thought escaped me for a second.
