### ISSUE TITLE
suggestion // version info at settings

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#178]
It seems like many apps have details at setting page.
Such as : Legalase, Support Manual, Feedback, Privacy, ToS, Open Source License, App Version Info...
'App Version Info' seems like the least detail that could be at settings menu.
Just thoughts.

**Comment by Ph1b** [comment]
Legalase is covered by information on google play and github.
Support is included in the hearth dialog
Feedback is included in the hearth dialog
Privacy is on Google Play and on GitHub (which is linked on the hearthdialog)
Opensource License is on GitHub (linked)
App Version Info should be provided by the system.
