### ISSUE TITLE
2.1.6 // Settings Duplicated

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#180]
Settings dialogue duplicated itself.

**Comment by JoshGraham** [comment]
In this order
General Settings - Playback Behavior - General Settings - Playback Behavior

**Comment by Ph1b** [comment]
What do you mean by that? How is it duplicated?

**Comment by JoshGraham** [comment]
- Steps to reproduce
Change into dark theme

- Expected behavior
Change into dark theme

- Actual behavior
Change into dark theme
and Settings duplicates

https://gist.githubusercontent.com/JoshGraham/43f54fec12e0cddd52a5/raw/cbe780e1306f07bea6f6a0292303d207ee3270e8/gistfile1.txt

![0](https://cloud.githubusercontent.com/assets/8502832/7386650/48e26270-ee91-11e4-8328-844797c6e69a.png)

**Comment by Ph1b** [comment]
That was a weird one. Fixed as of 60aab6b06225457249083b99464c4ed9683acaf2, thanks for reporting.
