### ISSUE TITLE
2.1.6.1 // Google Billing seems to be disabled

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#183]
tapping 1~20€ button does nothing.
still not sure it's a bug. Will try some more

**Comment by JoshGraham** [comment]
still not sure it is an issue
logfile
https://gist.github.com/JoshGraham/31595342795810a52311

**Comment by JoshGraham** [comment]
still not sure it is an issue
logfile
https://gist.github.com/JoshGraham/31595342795810a52311

**Comment by Ph1b** [comment]
Sure it is an issue. Thanks for reporting ;-) d6c815902a59d8f3dc7c0852f69cc1f61d548961
