### ISSUE TITLE
setting play chapter to end does not stop after end of chapter

### ISSUE THREAD

**Issue by thofrey** [Ph1b/MaterialAudiobookPlayer#184]
I must admit that it never worked on my device. I could do a adb logcat if this is helpful.
Sleeptime without setting "playing chapter to end" works fine. 
(Moto G, Android 4.4.4)

**Comment by Ph1b** [comment]
Thanks for the report. This was resolved by a spring cleaning ;-) https://github.com/Ph1b/MaterialAudiobookPlayer/commit/f57a1baf3acc4bbcf2956b1bbe5b6379634f7466

**Comment by thofrey** [comment]
Hi Paul,

I have just tested with the pre-release v2.1.7.

The setting "play chapter to end" is missing now. Perhaps I have tested with a too early version?

Many Regards,
Thorsten



Am 22. Mai 2015 03:31:25 MESZ, schrieb Paul Woitaschek <notifications@github.com>:
>Thanks for the report. This was resolved by a spring cleaning ;-)
>https://github.com/Ph1b/MaterialAudiobookPlayer/commit/f57a1baf3acc4bbcf2956b1bbe5b6379634f7466
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Ph1b/MaterialAudiobookPlayer/issues/184#issuecomment-104471285

Thorsten Frey
--
Diese Nachricht wurde von meinem  Mobiltelefon gesendet.

**Comment by thofrey** [comment]
Oops.

I had just a look at the code. You removed this feature !?

Thorsten 

Am 22. Mai 2015 22:51:36 MESZ, schrieb Thorsten Frey <thorsten@tfrey.de>:
>Hi Paul,
>
>I have just tested with the pre-release v2.1.7.
>
>The setting "play chapter to end" is missing now. Perhaps I have tested
>with a too early version?
>
>Many Regards,
>Thorsten
>
>
>
>Am 22. Mai 2015 03:31:25 MESZ, schrieb Paul Woitaschek
><notifications@github.com>:
>>Thanks for the report. This was resolved by a spring cleaning ;-)
>>https://github.com/Ph1b/MaterialAudiobookPlayer/commit/f57a1baf3acc4bbcf2956b1bbe5b6379634f7466
>>
>>---
>>Reply to this email directly or view it on GitHub:
>>https://github.com/Ph1b/MaterialAudiobookPlayer/issues/184#issuecomment-104471285
>
>Thorsten Frey
>--
>Diese Nachricht wurde von meinem  Mobiltelefon gesendet.

Thorsten Frey
--
Diese Nachricht wurde von meinem  Mobiltelefon gesendet.

**Comment by Ph1b** [comment]
Yeah, sorry. This is long-time no-functional and nobody even got it. So I think this is rarely used.
