### ISSUE TITLE
Openning Settings crashes the app

### ISSUE THREAD

**Issue by mabkenar** [Ph1b/MaterialAudiobookPlayer#186]
I have just installed Material Player from f-droid. How can I get and send you a log?

**Comment by Ph1b** [comment]
After crashing you can check the logcat like [explained here](http://stackoverflow.com/questions/2882253/how-do-i-get-the-logfile-from-an-android-device). If you reach the settings menu, from then on the auto bug report can be checked.

**Comment by mabkenar** [comment]
The issue is fixed aftrr an update. Sorry for my late reply, and thanks for your nice app.
