### ISSUE TITLE
Suggestion// Please add an opportunity to generate list of files in a folder

### ISSUE THREAD

**Issue by gladk** [Ph1b/MaterialAudiobookPlayer#187]
It would be good to have an opportunity to generate list of files in a folder. It is useful for podcasts, where new files can appear regularly.

Thanks

**Comment by Ph1b** [comment]
There are two ways to add books, which should suffice for most use cases. For your usecage:
if the files appear in /storage/podcasts/alternativlos/
just add that folder as a collection (not single book).
