### ISSUE TITLE
Empty database after a reboot

### ISSUE THREAD

**Issue by devstderr** [Ph1b/MaterialAudiobookPlayer#189]
Material Player Version 2.1.6.1 F-Droid.
Every time i power on my device the database
/data/data/de.ph1b.audiobook/databases/autoBookDB
is overwritten with an empty one.
If i start Material Player my books are scanned and stored in the database.
Also listening position and playback speed are stored.
Until the next power off and on.

**Comment by Ph1b** [comment]
Thanks for the report. Is this still happening here? https://github.com/Ph1b/MaterialAudiobookPlayer/blob/master/distribute/v2.1.7-pre1-debug.apk

**Comment by Ph1b** [comment]
As there is no more information I assume this has been resolved. If not please reopen.
