### ISSUE TITLE
Missing A2DP data

### ISSUE THREAD

**Issue by mase76** [Ph1b/MaterialAudiobookPlayer#190]
Hi!
I often use MaterialPlayer in my car, that can display the title data send
with A2DP. With MaterialPlayer the Album is missing, also the playtime is
not running. There is only a random value for the time.

**Comment by Ph1b** [comment]
Implemented as of 5ab4b423be0915ff032f304182b2bb4beb663e35 and coming in the next release. If this is not working, please reopen, have no car to test this ;-)

**Comment by Ph1b** [comment]
[here](https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/v2.1.9) we go

**Comment by mase76** [comment]
It works better than before. The timestamp is ok. But it shows the filename as title. The artist is empty. It shows the folder as album. Id3 should be used instead. Then it would be perfect.

**Comment by Ph1b** [comment]
Is there still any information missing?

**Comment by mase76** [comment]
The timestamp runs. The filename is shown instead of the track. The artist is missing. The foldername is shown instead of the album.

**Comment by Ph1b** [comment]
How is it if you really reinstall the app? The metadata is only read from the files once they get scanned. Later they stay in the database so you don't see the changes in recognition, only in displaying.

**Comment by mase76** [comment]
Did so. Now everything's fine! Thx!
