### ISSUE TITLE
Bug: Audio resumes right after connecting to Bluetooth event with "Resume Playback" unchecked

### ISSUE THREAD

**Issue by georgeplendl** [Ph1b/MaterialAudiobookPlayer#191]
Bug: Audio resumes right after connecting to Bluetooth event with "Resume Playback" unchecked

Nexus 6

**Comment by Ph1b** [comment]
I can't confirm this issue. Whether I have the option check or not checked, the app does not continue playback.
What are the excact steps to reproduce? Does it occur with other players with similar playback behaviour as well?

**Comment by Ph1b** [comment]
As there is no more response I assume this is resolved. If not, please reopen.
