### ISSUE TITLE
App freezes when book folder is deleted

### ISSUE THREAD

**Issue by Lawpoint** [Ph1b/MaterialAudiobookPlayer#193]
Just it. When I delete an audiobook folder after finishing a book, the app freezes at the next launch. Finally the system notification about non-responsive app appears, allowing to terminate the app, and next time it starts without an issue.

**Comment by Ph1b** [comment]
Thanks for the report. Which version are you using? Is this the case in 2.1.7?
https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/v2.1.7

**Comment by Lawpoint** [comment]
Just checked - the version I'm using is 2.0.9.1
Will update now.

**Comment by Ph1b** [comment]
If this is still present, please reopen.
