### ISSUE TITLE
Use track metadata if available

### ISSUE THREAD

**Issue by kevmitch** [Ph1b/MaterialAudiobookPlayer#194]
In the root menu for selecting books, the header at the top of the screen when the book is selected, and on the lockscreen, it displays the filename of the containing folder instead of the contents of "Album"/"TALB" tag in mp3 files (haven't tested other formats), which is typically used to identify the book title.

Similarly, the track list when a book is selected and the on lock-screen only a number identifying the currently playing track is displayed rather than the contents of the "Title"/"TIT2" tag. Strangely, with audiobooks where "TPOS" is set to group the book into first/second half, this value is displayed in preference to "TRCK" resulting in the very bad behaviour that ~20 tracks are all titled "1" and the final ~20 are titled "2".

Finally, the "Artist" / "TPE1", typically used for the book's author don't seem to be displayed anywhere.

As reported by id3v2 -l, a typical [emusic.com](http://emusic.com) audiobook's mp3 tags look like

```
id3v1 tag info for 01.part_1_of_6.mp3:
Title  : Part 1 of 6                     Artist: Douglas Coupland              
Album  : Hey Nostradamus!                Year: 2010, Genre: Blues (0)
Comment:                                 Track: 1
id3v2 tag info for 01.part_1_of_6.mp3:
TFLT (File type): MPG/3
TIT2 (Title/songname/content description): Part 1 of 6
TPE1 (Lead performer(s)/Soloist(s)): Douglas Coupland
TPE2 (Band/orchestra/accompaniment): Douglas Coupland
COMM (Comments): ()[]: Narrated by , John Randolph Jones, Jenna Lamia, Jillian C
TALB (Album/Movie/Show title): Hey Nostradamus!
TCON (Content type): Audiobooks (255)
TYER (Year): 2010
TRCK (Track number/Position in set): 1
TSIZ (Size): 33756171
APIC (Attached picture): ()[, 3]: image/jpeg, 17737 bytes
USER (Terms of use): [Cop]: yright notice. These materials are protected by United States copyright law and by international treaties. You may use these materials for your personal, non-commercial use only. You may not otherwise reproduce, distribute, publicly perform, publicly display, or create derivative works of these materials, unless authorized by the appropriate copyright owner(s).
```

And a [downpour.com](http://downpour.com) 

```
id3v2 tag info for 1.01.dedication.mp3:
TIT2 (Title/songname/content description): Dedication
TPE1 (Lead performer(s)/Soloist(s)): By Larry Niven
TRCK (Track number/Position in set): 1/35
TALB (Album/Movie/Show title): The Ringworld Engineers (Unabridged)
TPOS (Part of a set): 1/2
TYER (Year): 1979
TPE2 (Band/orchestra/accompaniment): By Larry Niven
TSSE (Software/Hardware and settings used for encoding): Lavf56.25.101
APIC (Attached picture): (Album cover)[, 3]: image/jpeg, 1326108 bytes
1.01.dedication.mp3: No ID3v1 tag
```

In the above example, there are 35 tracks for the whole book. TRCK= 1 - 19 are TPOS =1, while TRCK 20-35 are TPOS =2. The "parts" correspond the the splitting of the mp3s into two zip files. Alternatively, I could have downloaded 2 .m4b files, but I haven't tried that yet. This is probably the same splitting that you get if one were to use audible.

In any case, the point is that TRCK is more important that TPOS.

**Comment by kevmitch** [comment]
Ok, so it looks like the fact that I was getting just numbers for the track titles is related to the fact that my files were named 

01.part_1_of_6.mp3
1.01.dedication.mp3

apparently, it is stripping off everything after the first ```.```. If I replace these with ```-``` for instance, the full file name minus the extension are displayed as the track title.

So I guess there are really two issues:
1) metadata should be used if available
2) when using filenames for titles, extension removal should behave like python's os.path.splitext - everything after and including the **last** ```.``` is removed

**Comment by Ph1b** [comment]
I dont get it. Why are you using 
````java
String.indexOf('.')
````
instead of
````java
String.lastIndexOf('.')
````
When a track is called 01.tracktitle.mp3 then the title would be cut off?

**Comment by kevmitch** [comment]
I think you're reading the diff backwards. My change is the other way around.

**Comment by Ph1b** [comment]
Oops. Okay, implemented, thanks.

**Comment by Ph1b** [comment]
007b718c3d1d6f6726c4cc2421480bd016f9d361 implements to use metadata on the track if available with a number prefix.
edfaf51ebab8c4bbfa8cee21dc6e029ccc59f113 implements the dot index thing

**Comment by Ph1b** [comment]
0c73932627cdc3553232b4d03fe71ab2f0854ed9 implements to use metadata of the files for booktitle if available.

**Comment by kevmitch** [comment]
exciting! thanks. will try later tonight.

**Comment by Ph1b** [comment]
e5131d3e78f38a553e056725cb97315aaa1b27de implements more intelligent naming, so the tracknumber will be added in front of the title dynamically if needed, so this is robust against new files coming.

**Comment by kevmitch** [comment]
cool. just upgraded through f-droid and everything works great.
