### ISSUE TITLE
Hiccup on mp3 seeking and unpause

### ISSUE THREAD

**Issue by kevmitch** [Ph1b/MaterialAudiobookPlayer#195]
When seeking mp3 files, or unpausing (which implicitly involves a seek back a few seconds), there is a hiccup sound. There is no such hiccup when seeking with Google Music.

My wild speculation is that this is the result of playing an incomplete mp3 frame and could therefore be most simply solved by rounding seeks to the previous frame boundary.

**Comment by kevmitch** [comment]
If I manually disable playback speed by setting [playerCanSetSpeed](https://github.com/Ph1b/MaterialAudiobookPlayer/blob/master/audiobook/src/main/java/de/ph1b/audiobook/mediaplayer/MediaPlayerController.java#L34) to ```false```, this forces the AndroidMediaPlayer() to be used instead of CustomMediaPlayer(). 

In this case seeking works perfectly with no hiccups. 

Could be that something special needs to happen in [CustomMediaPlayer.seekTo()](https://github.com/Ph1b/MaterialAudiobookPlayer/blob/master/audiobook/src/main/java/de/ph1b/audiobook/mediaplayer/CustomMediaPlayer.java#L154). Though the documentation of [MediaExtractor.seekTo()](http://developer.android.com/reference/android/media/MediaExtractor.html#seekTo%28long,%20int%29) and [MediaExtractor.SEEK_TO_CLOSEST_SYNC](http://developer.android.com/reference/android/media/MediaExtractor.html#SEEK_TO_CLOSEST_SYNC) seems to suggest that it will seek to the closest "key frame", which in a sane world would be the beginning of an mp3 frame. So maybe the problem is really in [CustomMediaPlayer.decode()](https://github.com/Ph1b/MaterialAudiobookPlayer/blob/master/audiobook/src/main/java/de/ph1b/audiobook/mediaplayer/CustomMediaPlayer.java#L358), though I confess to not fully understanding what's going on there.

**Comment by Ph1b** [comment]
I mostly don' t understand the audio processing at all, so this need external help. I read somewhere that a flush on the codec should work, but I dont even know how to try that since I'm just getting an IllegalStateException each time I try that.

**Comment by kevmitch** [comment]
In the meantime, a less brute force way of disabling CustomMediaPlayer might be helpful.
