### ISSUE TITLE
Track selection screen: more track info

### ISSUE THREAD

**Issue by NeuroNex** [Ph1b/MaterialAudiobookPlayer#198]
It would be more user friendly if the track selection screen looks like the playlist view in most of music players. Important visual clues are: 
1. The current playing track is highlighted (either with different font color, a play icon, or a different background).
2. The duration of the track
3. The index of the track in the book. Example: "19. John Bell and his Theorem". Would be ideal to make the index display optional.

In other music player, the track selection screen usually takes the full screen. This improves navigation and gives more room for displaying more details.

**Comment by Ph1b** [comment]
Thanks for the feedback. Really helpful.

1. Implemented as of ec6d0842ce78c9bde3a9e49a2474b3bb4a96d241
2. As audiobooks are listened to continuously I think this is not necessary and would cause too much cluster.
3. This is the case as of [v2.1.9.1](https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/v2.1.9.1), but just for newly imported media. I did not want to interrupt users too much with waiting for a full import, so after unselecting the audiobook folder and readding it, this should work. Player should keep up to 70 books even if deleted I think. Pls report if not so.

**Comment by Ph1b** [comment]
Edit: 3 is for all media the case.

**Comment by kevmitch** [comment]
I disagree with making the track selection full screen. I always found that awkward, confusing and annoying in Google Music.

**Comment by NeuroNex** [comment]
Hi,

#1 (highlight playing track) not yet working. See screenshot below, the one on the left.

#2 Often audiobooks are split in several files. Each may have different duration. It is true that there are less files and the duration are longer than music files. Nevertheless, an indication of duration is nice. But not indispensable. To reduce clutter, you can display the duration in small font, right justified on the same line as the track title. If the title is too long, just display the duration on top of the title (with some space padding for better separation)

#3 Using v2.1.9.1 (this is the 1st time I use Material Audibook). I don't see index prefixing the track title. I have deleted audiobook folder and readded it, still no index number. The Index number you are seeing in the screenshot below is actually part of the title. I retag the title to prefix it with the track number.

@kevmitch Regarding the opinion of "making the track selection full screen": When you want to select tracks, what else do you want to see OTHER than the list of track? How come it is confusing when there is a single screen displaying track lists? I would think this reduce significantly the distraction compared to the partial track list which share the screen space with something else not relevant to the task. I'm not a GUI expert, but when you use an app like SMS texting for example, do you prefer the SMS app taking all the screen or half of the screen?

![trackselection_mavspoweramp](https://cloud.githubusercontent.com/assets/10089894/7898382/2a71d52a-06cc-11e5-992f-ed28a3a7968c.png)

**Comment by Ph1b** [comment]
# Highlighting
The commit was done after the release you use.

# Duration
Sorry but I dont find this important.

# Track prefixes
On your screenshot I can see prefixes. I.e 33 - ..., 34 - ...
Or did I completely missunderstand you?

**Comment by NeuroNex** [comment]
Hi,
The track number you see are those I hardcoded in the title. Which means I edited the MP3 title tag *"Risk Either Way"* and changed it to **30** - *Risk Either Way*.

As a verification, you just need to review your code to see if you use the format TrackNum (space) (dash) (space) Title.

**Comment by Ph1b** [comment]
That is on purpose, since we dont need two prefixes of the same kind. If you rename your track, and remove the prefix, it will stay the same.

**Comment by Ph1b** [comment]
This is the commit for the track naming: https://github.com/Ph1b/MaterialAudiobookPlayer/commit/e5131d3e78f38a553e056725cb97315aaa1b27de

**Comment by NeuroNex** [comment]
Hi,

Oh wow, confirmed. You went to the trouble of checking the content of the title to avoid adding a redundant track index. This is genius! Thanks.

Thanks
