### ISSUE TITLE
Sleep timer count down: improve visual clue when enabled

### ISSUE THREAD

**Issue by NeuroNex** [Ph1b/MaterialAudiobookPlayer#199]
**How can we know if the sleep timer is enabled?**
In version 2.1.9.1: we can notice that the sleep timer icon is slightly different. Suggestion: display a count down timer somewhere in the screen (lower left or right, or even in overlay on top of the album cover).

**Comment by Ph1b** [comment]
Approved. When I find time, I'll implement a little circle in the top right corner (like the current playing icon on the BookShelf) displaying the time left for the sleep timer. If someone wants to implement this, I'd appreciate this ;-)

**Comment by Ph1b** [comment]
Thanks a lot skynetua !
