### ISSUE TITLE
Adding Sound Volume Setting

### ISSUE THREAD

**Issue by NeuroNex** [Ph1b/MaterialAudiobookPlayer#200]
Because the sound level of each book is different, it is very convenient if we can set the sound volume directly from the player without using the hardware volume button. There are two possible ways to implement that features:

1. Add a Sound icon. When tapping on it, a sound level slider appears to allow setting the sound with the finger.

2. By gesture: for example swipe up/down on the cover will increment/decrement the sound volume. Let's say each swipe will inc/dec by 10%. Example: sound volume currently at 20%. I want to increase it to 50% and then swipe up 3 times.

BTW, the top toolbar can be used to host more icons. So far a big portion of that toolbar is wasted to echo the album title, which is already clearly indicated in the album cover.

**Comment by Ph1b** [comment]
I dont think this is necessary. I think this should be handled by the user. What would something great is normalizing the loudness, but thats nothing I'm able to.

**Comment by NeuroNex** [comment]
This is low priority and maybe you will recognize its usefulness one day.

Normalizing the loudness would be overkill I think. The idea I suggested above is that it's more convenient to have an "on screen" command to control volume as opposed to hitting the hardware volume control button. The most convenient is the swipe up/down on the cover to control volume as in [Listen Audiobook Player](https://play.google.com/store/apps/details?id=com.acmeandroid.listen)

This seems strange but here is how I am used to control volume:

- When the device is in the pocket, I use hardware button

- When I am interacting with the app, I prefer the on screen volume button supplied by the app. This seems to be a growing trend. [OverDrive](https://play.google.com/store/apps/details?id=com.overdrive.mobile.android.mediaconsole) now also has a volume button since maybe last month, when the app has had a GUI update.

**Comment by NeuroNex** [comment]
Regarding sound setting, another idea I think would be useful is the possibility to boost the volume above the normal range. I think this is kind of volume multiplicator. Both apps mentioned above (Overdrive and Listen Audiobook Player) have this setting.

Some audiobooks have low volume level. I can't hear well in a loud environment like public transit. Enabling the volume boost fixes the issue.
