### ISSUE TITLE
Go back to Playing screen by back button (from Album/Books list view)

### ISSUE THREAD

**Issue by NeuroNex** [Ph1b/MaterialAudiobookPlayer#201]
**How to go back to the album playing screen?**

- In v2.1.9.1, play a track. While the track is still playing, tap on the toolbar where there is the title of the album to go to the album selection screen.

- Browse around the list of available albums. Let's say we don't want to change album, and just want to return back to the playing screen.

- Tapping on top toolbar, nothing happen, Tapping back button the app show the home screen (while still playing). The only way to go back to the playing screen is to select exactly the current playing album/book and select it.

**Suggestions**

1. Allow to go back to playing screen by tapping back button.
2. Add a play icon somewhere on the toolbar (which currently displays "Material Player"). Tap on that button also returns to playing screen.

**Comment by Ph1b** [comment]
Implemented (current playing in bookshelf toolbar) as of ee2b53967f7409190f6115658688978a16c9d749.

I don't want the app to go back to playing screen because that should be the start of the hierarchy, so you always know how to leave and where the back button will take you next.

**Comment by NeuroNex** [comment]
I suppose commit [ee2b539](https://github.com/Ph1b/MaterialAudiobookPlayer/commit/ee2b53967f7409190f6115658688978a16c9d749) is not yet released?

(Using Material Audio book v2.1.9.1 as of 2015-05-30)

**Comment by Ph1b** [comment]
Correctly, that will be in the next release ;-)
