### ISSUE TITLE
how to buid non-debug .apk?

### ISSUE THREAD

**Issue by kevmitch** [Ph1b/MaterialAudiobookPlayer#207]
Stupid question. 

Up to now, I've just been using android studio to "Run" over adb on a physical device. This process appears to create ```/audiobook/build/outputs/apk/audiobook-debug.apk``` and ```./audiobook/build/outputs/apk/audiobook-debug-unaligned.apk```.

From reading the [docs](http://developer.android.com/tools/building/building-studio.html), it sounds like I should be able to create a non-debug version with Build->Make Project, which I can then manually install on my device myself. This appears to run without error, but does not generate any .apk files at all.

I'd love to hear that there's an simpler command line way to build a non-debugging .apk, but I'll settle for a working android-studio method.

**Comment by kevmitch** [comment]
Or does "debug" just mean not signed for the release / play store? I'm used to it meaning "not optimized". 

Even if so, shouldn't Build->Make Project generate *something*?

**Comment by Ph1b** [comment]
A debug version is a version that does not need proper signing and has many developer things (like enhanced logging) enabled. Also proguard is turned off, so the app will have a larger size. Also building is faster, so this is the way for developing. The signing key is secret and only on my machine. It makes sure that the app updates are always certified by the developer.

Having said that  on the left of android studio you can click on "Build Variants" and choose the release version. But there should be an error if you dont configure a signing keystore.

To test an app, simply click on the top on the little play botton next to the module (in this case "audiobook").
