### ISSUE TITLE
Notification Bar functionality

### ISSUE THREAD

**Issue by ikonomov** [Ph1b/MaterialAudiobookPlayer#208]
I have a few suggestions to improve the usability of the notification for the player.  I really like how Shuttle Music Player's notification bar functions, and I wish your player's notification bar functions the same way.
1. When the player is open, there is NO notification in the notification bar, both when it's playing and when paused.
2. When the player is open and the playback is paused from the interface, and then the phone switches to another app or goes to the home screen, there is NO notification.
3. When the player is open and playing, and then the phone switches to another app or goes to the home screen, a notification appears in the notification bar (and lock screen).
4. When the player is not open, but playing, pausing the playback from the notification bar (and lock screen) does NOT close the notification.

**Comment by Ph1b** [comment]
I like it this way, its much less efford in programming. If you dont need the notification any more and it is paused, just swipe it away.
