### ISSUE TITLE
add +db (equalizer) control for loud Books

### ISSUE THREAD

**Issue by BudSpencerr** [Ph1b/MaterialAudiobookPlayer#211]
I have some loud Audio books even on lowest volume setting there are to loud for sleeping.
As example PowerAmp has an PreAmp function wich allows you to decrease the volume.

**Comment by Ph1b** [comment]
I dont have any idea how to implement this. I tried to set up the android Equalizer class, but this turned out to be extremely buggy.
https://github.com/Ph1b/MaterialAudiobookPlayer/tree/equalizer
If someone is able to write fine controls about the audio processing, feel free to.
