### ISSUE TITLE
Audio speed way too low on some MP3 files

### ISSUE THREAD

**Issue by Marxsal** [Ph1b/MaterialAudiobookPlayer#213]
I just downloaded and installed MAP from the Playstore. V 2.1.9.1.

On the first book I tried it worked great. I played with the sound speed and increased it a bit. Then I tried MAP on a set of newscasts from NPR in a different directory. The sound plays at about quarter speed or lower. No speed adjustments can bring it up to normal sound.

The files for the first book I tried continue to play fine. But the others are unusable at the current speed.

Thanks!

Additional note #1: It's not just SLOW, it's also LOW pitched. Like a phonograph running out of power.

**Comment by Ph1b** [comment]
Can you please post the output of this app?
https://www.dropbox.com/s/catp8qgwuvmbosi/app-debug.apk?dl=0
(allows copy & paste)

Also see https://github.com/Ph1b/MaterialAudiobookPlayer/issues/129

**Comment by Ph1b** [comment]
Does this version work fine with all your files? https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/v2.1.8

**Comment by Marxsal** [comment]
The debug app appears to be buggy -- lacks the "copy" option that would allow me to copy results. The upper bar that would usually have the copy option is blank. Is there some particular part I can read off?

**Comment by Marxsal** [comment]
I assume I was supposed to test v2.1.8-pre1-debug in the preview directory?

It also has the low speed/low voice problem.

**Comment by Ph1b** [comment]
Try this one, this one has an apk: https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/v2.1.7

For selecting text, long click the text and select all, then copy.

**Comment by Ph1b** [comment]
Please post in this thread: https://github.com/Ph1b/MaterialAudiobookPlayer/issues/129
