### ISSUE TITLE
Not playing any audio

### ISSUE THREAD

**Issue by jfml** [Ph1b/MaterialAudiobookPlayer#214]
Thanks for the awesome work! 

The player was working fine for me (I'm on Cyanogenmod11, Android 4.4.2) until an update some time ago (using F-Droid). Now the player seems to work, I can press play and it changes the button (so I can press pause, the widget also appears on lockscreen/dropdown) but there is no sound and the player always stays at 0:00. Same thing when I skip to another position on a track. Further updates didn't change anything (I'm now running 2.9.1.9) and neither did uninstalling/clearing data.

Mh, version 1.4 seems to work, but 2.0 doesn't but I'm pretty sure I had a version after 2.0 working.

If you need me to provide any logs or something else I'd be happy to provide more info.

**Comment by Ph1b** [comment]
Did you try different types of music files? The metadata (track duration etc) are displayed correctly?

**Comment by jfml** [comment]
Interesting! I use mp3 almost exclusively but tested the following now: mp3, m4a, ogg, oga, wav (all on 2.9.1.9). Metadata seems to be okay for all formats (including mp3), m4a works (except for one file where they playback speed seems to be really slow, it's speech and I can't understand anything because it's so slow even if it is on 1 or if I turn it up to 2). ogg, oga and wav work fine too, only mp3 playback doesn't work at all.

Mh, there's also an issue where the player almost always freezes/crashes when I open the program, play/pause something and then change to another folder and try to play a file there. But that might be for another time … #___#

**Comment by Ph1b** [comment]
This seems to be device specific as you seem to be the only user having this problem.
