### ISSUE TITLE
High power usage during playback.

### ISSUE THREAD

**Issue by kevmitch** [Ph1b/MaterialAudiobookPlayer#215]
I've done a few measurements and found that the player typically uses 2.6 %/hr (sorry getting the actual wattage seems to be impossible) whereas, Google Music uses about 1.7 %/hr. CyanogenMod's Apollo player from F-Droid seems to do about the same, so it doesn't look like there's any spooky proprietary power management going on there. 

It seems that some of it is related to the CustomMediaPlayer, because with the AndroidMediaPlayer, it drops down to around 2.2 %/hr. My guess for that contribution is that it's a performance hit for moving from native to java code, or is the pitch correction actually computing something even at 1.0 speed?

I'm not sure what else could account for that 0.5 % though. . .

**Comment by Ph1b** [comment]
Can you check this one? https://github.com/Ph1b/MaterialAudiobookPlayer/blob/master/distribute/66-develop-preview1.apk
Its basically the CustomMediaPlayer but without Sonic (speed lib) included.

**Comment by kevmitch** [comment]
Looks like the no sonic version is pretty close to the regular custom media player. 

I've figured out how to get some more sensible measurements from /sys/class/power_supply/battery/. Common sense suggests that voltage_now is reported in uV and current_now is reported in mA (or at least those give a reasonble order of magnitude for the wattage).

Player       | Power 
------------- | ------------- 
 Google Play Music | 220 mW
AndroidMediaPlayer | 240 mW
CustomMediaPlayer | 280 mW
NoSonic | 280 mW

**Comment by Ph1b** [comment]
Whats with the latest version? I made the idle communication more efficient, so maybe that lead to less power usage?

**Comment by kevmitch** [comment]
Still 280 mW as of 90e824d55afe86a9a2b689f3c54a752677c326d7

**Comment by Ph1b** [comment]
So its mostly the fault of the MediaExtractor implementation which cannot be avoided.
