### ISSUE TITLE
Cannot access audio books which have their size above 2gb

### ISSUE THREAD

**Issue by Bharathcountryboy** [Ph1b/MaterialAudiobookPlayer#217]
With prior thanks I would request that this important feature is add so that it helps people who convert large books into an audio file and use this special app to access. Not to forget this app is so cool and simple. This is the best audiobook player so far I seen but for the fact that this player cannot play audio file that is above 2Gb, I've much files which are like 4.2Gb etc, so it would be helpful if this player makes it happen.

Uploads has a image (1)of the folder which contains audio books and (2) out of those three books in the folder one book which has been accessed by the app,.

Thanks again 
Bharath A
![screenshot_2015-06-09-02-23-19](https://cloud.githubusercontent.com/assets/12803723/8045154/1ed03a2e-0e4f-11e5-94e9-411d26bccdcd.png)
![screenshot_2015-06-09-02-22-27](https://cloud.githubusercontent.com/assets/12803723/8045164/308aea48-0e4f-11e5-8316-fc7bf6940810.png)

**Comment by Bharathcountryboy** [comment]
Someone please solve this problem, add the feature, do something it's a kind of issue which has to be dealt with. Thank you

**Comment by Ph1b** [comment]
Can you play the file with other players?

It more seems to be a problem with [your partition](https://groups.google.com/forum/#!topic/android-porting/alF-avcQNfI). Dont see anything the player could do about that.

**Comment by Bharathcountryboy** [comment]
Yeah with other players like MX player, and vlc am able to play those, thank you.

**Comment by Ph1b** [comment]
And using the same file? What if you delete all the books from the library and add the problematic file as a single book (not collection)?

**Comment by Bharathcountryboy** [comment]
I have tried it, I went on to select 7 files individually, from other folders as well which are above 2gb, and the results was same the files won't even appear in the list.

**Comment by Bharathcountryboy** [comment]
I directly selected the books and even the folders as well.

**Comment by Ph1b** [comment]
Cannot confirm this. Can anyone? I tried it with a file 8gigs large but no problem.

**Comment by Ph1b** [comment]
If there are any news on this, please reopen.

**Comment by Bharathcountryboy** [comment]
This problem is not only in my device it's actually same in all of my friends mobile, I've tried lot of people the files with 2gb higher size are not seen with the others below 2gb

This is same even after 2 updates, may be you could access the files with mp3 format, I don't know whether this problem only occurs when with .wav format files,.

If the files you have test are of mp3 one's then even I would convert .wav files to mp3 and look at it... 

Thank you

**Comment by Bharathcountryboy** [comment]
Has anything happened in this regard... 
Thank you

**Comment by Bharathcountryboy** [comment]
Is this thing neglected..

**Comment by Ph1b** [comment]
Nope. Everything that is not close is not neglected. Is has the bug label, so it is considered a bug.

I don't have a lot of time right now due to work and upcoming baby, so if anyone wants to dig into it, feel free to.

**Comment by Bharathcountryboy** [comment]
Upcoming baby! Wow!!

That's fine bro,, thanks for replying ☆ ☆ ☆

**Comment by Ph1b** [comment]
Still cannot confirm this. Tried it with various files with their size above 2gb. If someones investigation give any sucess, please report!
