### ISSUE TITLE
The player cannot play APE audio files

### ISSUE THREAD

**Issue by Bharathcountryboy** [Ph1b/MaterialAudiobookPlayer#219]
With prior thanks I would request u to add support  to play APE files.
Thanks again 
Bharath A

**Comment by Bharathcountryboy** [comment]
Someone consider this

**Comment by Ph1b** [comment]
This seems to be [no free codec](https://en.wikipedia.org/wiki/Monkey%27s_Audio) and thus not supported by the android platform.
