### ISSUE TITLE
Seeking with slider always returns to first track 

### ISSUE THREAD

**Issue by kevmitch** [Ph1b/MaterialAudiobookPlayer#220]
As of the most recent commit 93ac4cd41166d8b3925a91b06676d3ec883c4efa, seeking with the slider will seek back to the selected time in the *first track* of the book, not the currently playing one as expected. The incremental seek buttons however work as expected.

**Comment by Ph1b** [comment]
Yeah, already have that one on mind. I started a 7-weeks freelance
project while that I have little time for MAP. But afterwards I take
some father-time where I'll have some more time again.

But I think I can fix these on the weekend.

**Comment by Ph1b** [comment]
Fixed as of b867b0ad9ec2d62443d26cb593dc828a4c70d2a1
