### ISSUE TITLE
Ability to skip files in screen off mode

### ISSUE THREAD

**Issue by zelenij** [Ph1b/MaterialAudiobookPlayer#222]
I have a suggestion: in CynagemMode M12 it is possible to skip to the next track (read - next MP3 file) by long-pressing volume up when the screen is off.  It would be great if MAP supported this feature as well.

Failing that, at least a next track button on the lock screen widget would be welcome.

I'm happy to help with code writing if you could point me to the relevant code sections.

**Comment by kevmitch** [comment]
Please do not change the current volume long press action which is to seek, not skip. This is much more useful for audiobooks IMO and is the reason why I started using MAP in the first place.

I imagine there are space constraints in adding this to the the lock-screen card, which Google has made almost uselessly tiny. Maybe this could fit on the enlarged lock-screen card.

**Comment by zelenij** [comment]
How about an option to toggle between the two types of behaviour?

* Long press skips
* Long press seeks

**Comment by Ph1b** [comment]
I redirected these clicks on purpose as I think navigating within a track is much more useful as we are no music player and books are mostly heard straight from start to end. And I dont want the app to be bloated with features.
