### ISSUE TITLE
Feature Request: Volume Boost

### ISSUE THREAD

**Issue by SaltwaterReef** [Ph1b/MaterialAudiobookPlayer#223]
Just like "Podcast Addict" I would like to see a Volume Boost for books where the recording is rather low.  This would be set per book.

**Comment by Ph1b** [comment]
I tried the volume boost supported by the android platform in the [equalizer branch](https://github.com/Ph1b/MaterialAudiobookPlayer/tree/equalizer) but it caused a lot of problems on various platforms, so sorry this is not possible right now.
