### ISSUE TITLE
App loses current position when switching chapters

### ISSUE THREAD

**Issue by RayBB** [Ph1b/MaterialAudiobookPlayer#224]
Currently if I switch from one chapter to the next (to see how long the next chapter is) and then go back to the orthogonal chapter it will start playing at 00:00 instead of where it was when I left.

Also, I think it would be helpful if the length of a chapter (mp3) was displayed next to it's name.

**Comment by Ph1b** [comment]
That is intended. In future versions that was possible but I thought that as confusing.

When a user tires to find a position and is too far in the future and is listening for about 1 minute of the unheard track but then goes back and back, hearing here and there a bit, then in the end when he continues listening, the player would jump directly to a position in the track but skip the initial minutes.
