### ISSUE TITLE
Title cut off

### ISSUE THREAD

**Issue by lightonflux** [Ph1b/MaterialAudiobookPlayer#225]
Filename: BF006\ -\ The\ Marian\ Conspiracy.mp3 
Title tag: (DW-BF-006) Doctor Who - The Marion Conspiracy

In MAP it appears as "(DW-BF-006) Doctor Who", without the episode part of title. 

I understand that the files are not well tagged. But i don't understand why MAP cuts the title so short. As it won't be displayed in the GUI anywhere, but doesn't allow the user to edit the real title tag in edit mode, instead i can only edit the shortened title which doesn't include the episode title anymore because MAP has thrown it away.

**Comment by Ph1b** [comment]
Can you send me one of these files to woitaschek@posteo.de so I can check?

**Comment by Ph1b** [comment]
With the file you sent me I can't confirm this. Make sure to always use the latest version available. 

Which android version do you use? Where does the problem occur?

**Comment by Ph1b** [comment]
![screenshot_2015-06-15-08-34-24](https://cloud.githubusercontent.com/assets/743462/8154420/43ba2080-133a-11e5-9d4c-b5dbf886890e.png)

**Comment by lightonflux** [comment]
Oh sorry i did not realise that the edit dialogue uses the album tag. 

In this case and many other the album tag is used for the series, not for the book.

So it is not a bug in the code. But the assumption that album equals book title is not always reality.
