### ISSUE TITLE
Text relocations warning when installing 2.1.9.1 apk

### ISSUE THREAD

**Issue by dandv** [Ph1b/MaterialAudiobookPlayer#226]
After `adb install map-v2.1.9.1.apk `:

```
WARNING: linker: app_process has text relocations. This is wasting memory and is a security risk. Please fix.                                                                                                       
        pkg: /data/local/tmp/map-v2.1.9.1.apk                                                             
```

**Comment by Ph1b** [comment]
This might be related to [xposed](http://stackoverflow.com/questions/22577315/warning-linker-app-process-has-text-relocations-this-is-wasting-memory-and-is)?

**Comment by dandv** [comment]
It was because of the xposed framework indeed. The error no longer appears after removing it.
