### ISSUE TITLE
Pause is not immediate

### ISSUE THREAD

**Issue by rajabalaji-mp** [Ph1b/MaterialAudiobookPlayer#228]
Hi,

Good work with the player, Awesome! 

In the lock screen, pause button on the player widget isn't immediate. It pauses after about ~5 seconds.

**Comment by rajabalaji-mp** [comment]
I have observed that it works fine some times, I guess it depends on the length of the video.

**Comment by Ph1b** [comment]
1. Is this everywhere the case? Like from lock-screen, widget, direct player?
2. Is it always with the same files?
3. Are they the same length?
4. Is this the case with the latest version?
