### ISSUE TITLE
Seeking with 2x playback speed

### ISSUE THREAD

**Issue by rajabalaji-mp** [Ph1b/MaterialAudiobookPlayer#230]
Hi, While seeking with 2x playback speed, it resumes at the time position thats half of it.

**Comment by Ph1b** [comment]
What do you mean by that? Can you write down an example what it does and how it should do?

**Comment by rajabalaji-mp** [comment]
Scenario: When I listen to an audio with 2x speed, and when I press forward or backward button:
Example: I am on the 9th minute of the video, and my backward button is set to take me 10 seconds back, when i press it once, It is supposed to go to 8 minute and 50 seconds rather it goes to 4 minute and 25 seconds, exactly the half of it. Same happens with the forward button as well.

Same happens when i seek to a certain time by dragging along the timeline.

Hope this helps.

**Comment by Ph1b** [comment]
Does this still happen with the latest version?

If so, please send me an example file to woitaschek@gmail.com so I can check it.

**Comment by Ph1b** [comment]
If this still exists, please reopen with the additional information requested.
