### ISSUE TITLE
audio is not pausing during small interruptions

### ISSUE THREAD

**Issue by dark-seizo** [Ph1b/MaterialAudiobookPlayer#232]
When a short sound plays while an audiobook is playing (google maps voice directions, text message notification tone) the app doesn't pause, it mutes itself and unmutes after the short sound completes, continuing as if it wasn't interrupted.

Is anyone else having this issue?  I'm looking into it atm I'll make a PR if I can fix it.

My device is a OnePlus One, running on 4.4

**Comment by Ph1b** [comment]
Maybe Pause on interruption is checked?

**Comment by dark-seizo** [comment]
Hmm, nope it wasn't checked!  Though I guess it still may be a bug, as when the short sounds play (with pause on interruption unchecked) the book is not audible on my device.

**Comment by Ph1b** [comment]
Why did you close?
