### ISSUE TITLE
Covers mixed

### ISSUE THREAD

**Issue by M3tthew** [Ph1b/MaterialAudiobookPlayer#238]
I don't know how but covers are mixed from one books to other.
And also a player create a whole album at my phone with covers of books, i don't like this fact.

**Comment by Ph1b** [comment]
That was an error in upgrading the database. But when re-installing the app or opening new books, that should not happen.

Can you open a new ticket describing what you mean with?
> And also a player create a whole album at my phone with covers of books, i don't like this fact.
