### ISSUE TITLE
Cover of books at my photos

### ISSUE THREAD

**Issue by M3tthew** [Ph1b/MaterialAudiobookPlayer#240]
player create a whole album at my phone with covers of books, i don't like this fact
here is how it looks at my phone. brand new album for covers of audiobooks
http://www.dropmocks.com/mJDtz5

**Comment by Ph1b** [comment]
Can you check where those files are? In earlyer versions of the player, the covers were stored seperately next to the audio books, but for about 2 month now that is no longer the case. So the current player should not generate any pictures. Also the previously generated pictures should appear as hidden.
If you can find out the location that would be really helpful.

**Comment by Ph1b** [comment]
Thats definately from previous versions, should not happen any longer (since a while now).
