### ISSUE TITLE
Ask user to hide the folder from other players

### ISSUE THREAD

**Issue by Ph1b** [Ph1b/MaterialAudiobookPlayer#242]
Ask the user if we should add a .nomedia file on adding a book collection. That leads in regular players not recognizing the audiobooks as music files any longer.

**Comment by dark-seizo** [comment]
Dang, almost had this one done.  We basically did the same thing though, yours of course was better ;)

**Comment by Ph1b** [comment]
Dann it :-/ in the future let's write a "working on this". Thanks anyway ;-)
