### ISSUE TITLE
Play button not in position

### ISSUE THREAD

**Issue by em-a-il13** [Ph1b/MaterialAudiobookPlayer#244]
I really like this app.
With the last update the button for play is not in a row with the others. It is at the bottom of the screen when in landscape view. 

![screenshot_2015-06-28-20-22-09](https://cloud.githubusercontent.com/assets/13089356/8397673/ed6f442c-1dd3-11e5-8e0e-8d5264c9587e.png)

**Comment by Ph1b** [comment]
Fixed as of bfb881c263c70df40492a1acfe951e6cf9b08567
