### ISSUE TITLE
Consider this much important ; reopening ticket #217 player cannot access audio books which have their size above 2gb

### ISSUE THREAD

**Issue by Bharathcountryboy** [Ph1b/MaterialAudiobookPlayer#246]
This problem is not only in my device it's actually same in all of my friends mobile, I've tried lot of people the files with 2gb higher size are not seen with the others below 2gb

This is same even after 2 updates, may be you could access the files with mp3 format, I don't know whether this problem only occurs when with .wav format files,.

If the files you have test are of mp3 one's then even I would convert .wav files to mp3 and look at it...

Thank you

**Comment by Ph1b** [comment]
Duplicate #217

**Comment by Bharathcountryboy** [comment]
Dude y dude!! Add a feature instead y to close it

**Comment by Ph1b** [comment]
I closed this 4 days ago when I reopened #217. Only one thread per problem is enough.

**Comment by Bharathcountryboy** [comment]
Oh OK thank you for considering..
