### ISSUE TITLE
Support for .mp3package file extension

### ISSUE THREAD

**Issue by dalb8** [Ph1b/MaterialAudiobookPlayer#248]
A certain app that provides audiobooks to public libraries stores its non-DRM'd mp3 files with the extension .mp3package under primary_storage/Android/data/application_id.

I added it to FileRecognition.java and it works fine. Only the title of the audiobook is useless but there's a decent picture.

**Comment by Ph1b** [comment]
Are you talking about audible?

**Comment by dalb8** [comment]
Bolinda. BorrowBox is the app name.

**Comment by john-french** [comment]
Came across this issue while searching for a player to play audiobooks downloaded with BorrowBox. I've since become a happy Voice user.
