### ISSUE TITLE
RFE: Ability to view details about a book on the main library screen

### ISSUE THREAD

**Issue by gshipley** [Ph1b/MaterialAudiobookPlayer#252]
Hi, I have cloned the repo and would like to start working on the following feature if you agree that it would be nice to have in the product.

On the main library screen,the user should be able to view details about the book including the summary.

How do I plan to implement this:  If the directory the book is located in contains a .nfo file, this file will be used.  The user must understand that any content in that file will be displayed on the device in a window that pops when they select to view book details.

**Comment by Ph1b** [comment]
Sorry but I find this to specific for really technical users. So I would like to keep it simple.
