### ISSUE TITLE
Just tapping or touching anywhere on the screen will stop the the process of reading

### ISSUE THREAD

**Issue by Bharathcountryboy** [Ph1b/MaterialAudiobookPlayer#254]
Even though there appears a botton or a key to pause and resume, the whole screen while in a reading process works as the pausing key, just a tap anywhere on the screen would stop the reading process, so my request is to make the pausing and resuming option limited with the key only.
Thank you.

**Comment by kevmitch** [comment]
I don't really care either way, but I've heard other users praise this feature.

**Comment by Ph1b** [comment]
That's intended behavior.

**Comment by Bharathcountryboy** [comment]
That's a disturbing feature I say, than what for the the specific key is provided, remember android's best player is mx which removed same option in 2014, if this is same then bye bye👋👋 material book player.. Thanks for serving..

**Comment by Bharathcountryboy** [comment]
But cancelling this feature would improve this App. Thank you
