### ISSUE TITLE
group books

### ISSUE THREAD

**Issue by ths80** [Ph1b/MaterialAudiobookPlayer#256]
For audiobook series like "Die drei Fragezeichen" ("The Three Investigators") with over 160 episodes it would be nice to group them in  a sub folder.

**Comment by duckpuppy** [comment]
I am in agreement with this one - I am working through the Doctor Who audio dramas which number almost to 200 now just for the monthly audiobook releases, and the ability to group them in the interface would be awesome.

**Comment by Darkmatter81** [comment]
You can already do this if I'm understanding the both of you correctly. I have multi-part audio books. I'll describe my setup. 

1. I have  set my folder to /storage/sdcard/Audiobook. Eg. Folder with multiple books

2. I create a sub folder within this main Audiobooks folder and place my multi-part book files into this folderfolder. 

3. I ensure that the meta data of each file is correct and alphabetical order 

Then in Material Player I see the multi part book is grouped as one item and each part is accessible via a drop down on the title.

**Comment by Ph1b** [comment]
I like to keep the structure simple, so there wont be a special grouping.
What you can do is add the whole series as a single book folder and listen to it sequentially.

**Comment by duckpuppy** [comment]
That doesn't work with the problem listed in #261 - unless the metadata is constructed such that it sorts alphabetically, then they won't sort sequentially.
