### ISSUE TITLE
Intermittent crashing and cover art problems

### ISSUE THREAD

**Issue by Icy13** [Ph1b/MaterialAudiobookPlayer#257]
Since the last two updates, I've been getting intermittent crashes and cover art displays with clipped edges (not just stretched to fit the window, but cropped) 

I'm not sure how to send a log file, but basic specs of my device
Sprint Samsung Galaxy Note 3 
Android 5.0 (most recent official released version for my device)

**Comment by Ph1b** [comment]
Did you enable auto crash reports? Which device are you using?

**Comment by Ph1b** [comment]
As there is no response I see this as done. If not, please reopen the ticket.
