### ISSUE TITLE
Cover art handling

### ISSUE THREAD

**Issue by Icy13** [Ph1b/MaterialAudiobookPlayer#258]
The app handles cover art a bit oddly. Even if I change the art in the audio book file, material player sticks with the cover from the first version of the file it ever saw. 

Please add the ability to update cover art when  file is loaded or reloaded. Maybe a preferences menu option to force a reread of id3 tags?

**Comment by kevmitch** [comment]
This problem is more general. If any of the files' metadata is changed, you must remove the book and re-add it before the changes will be visible in MAP.

**Comment by Ph1b** [comment]
This is covered by #300 #301 #302
