### ISSUE TITLE
(suggestion) 2.2.2 / animation at tap

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#259]
![github](https://cloud.githubusercontent.com/assets/8502832/8636527/200a0e34-28a2-11e5-8c20-346e1cd3f914.JPG)

I'd always wished that oval-shaped animation to be round and round.

Just thoughts. :-D

**Comment by Ph1b** [comment]
Should be fixed as of the last version.
