### ISSUE TITLE
Ability to sort items multiple ways.

### ISSUE THREAD

**Issue by duckpuppy** [Ph1b/MaterialAudiobookPlayer#261]
I have several audiobook and audio drama series that are meant to be listened to sequentially.  I also tag the files with the "correct" individual information, which means I don't have titles like "Series Book 1 - Book Title", I just have "Book Title".  I do name the files such that they group together and are sequential, though.  It would be nice to be able to choose to sort the book list by file name as well as by book title.  That would also help with longer series like the Discworld books where later books may reference earlier books but are different enough where it doesn't make as much sense for the actual metadata to reflect which book out of 30+ books published it is.

**Comment by nvx2004** [comment]
Yes, please. Sorting the library by file name would be awesome.

**Comment by Ph1b** [comment]
Sort of the same as #256

**Comment by duckpuppy** [comment]
This isn't the same at all - that's about grouping, and this is about sorting.  I want to sort separate books by something other than title, like file name.
