### ISSUE TITLE
Waze interruptions rewinds audiobook to random position

### ISSUE THREAD

**Issue by adilorlando** [Ph1b/MaterialAudiobookPlayer#264]
I have Material Player set to pause interruptions. When playing an audiobook while using the Waze app, any alerts or navigation prompts from Waze correctly pauses playback of the audiobook. However, Material Player seems to resume playback at a random spot anywhere from 2-60 seconds back. On occasion, I think it may actually jump ahead 2 seconds.

It's hard to pinpoint how long it skips backward since I'm driving when this happens but it may be tied to the length of the interruption. A long voice instruction from Waze seems to rewind the audiobook further. Ultimately, I lose my place in listening every time there's an alert from Waze which can be frequent during long trips.

**Comment by Ph1b** [comment]
Thanks for the report. There is a setting for automatically rewinding on each pause. That is what might confuse you. I updated the app, so the small pauses won't cause a rewind, so only the 'real' pauses cause one.
Can you try if it works [with this version?](https://github.com/Ph1b/MaterialAudiobookPlayer/blob/develop/distribute/77-preview-1.apk)

**Comment by adilorlando** [comment]
Had a chance to test this morning. The update you provided appears to have fixed the issue. It pauses and resumes in the same place. Thanks!
