### ISSUE TITLE
re-offer APK

### ISSUE THREAD

**Issue by Yma981** [Ph1b/MaterialAudiobookPlayer#265]
Please can you re-offer .apk, since some of us don't have google installed. We used to download the apk from the latest release in this site.

https://github.com/Ph1b/MaterialAudiobookPlayer/releases

**Comment by Ph1b** [comment]
You can get the last version on fdroid: https://f-droid.org/repository/browse/?fdid=de.ph1b.audiobook
(atm their build server hangs a bit.)

**Comment by Yma981** [comment]
10x

**Comment by Ph1b** [comment]
10x?

**Comment by Ph1b** [comment]
What did you mean by 10x?

**Comment by Yma981** [comment]
10x Means "Thanks"
