### ISSUE TITLE
id3 encoding

### ISSUE THREAD

**Issue by skynetua** [Ph1b/MaterialAudiobookPlayer#275]
Add windows-1251 encoding to utf8 while metadata reading. It causes problems with Cyrillic symbols.

![6636745](https://cloud.githubusercontent.com/assets/3670941/9131564/68b05f6e-3cf5-11e5-97e7-a7fb763c7928.png)

**Comment by Ph1b** [comment]
Can you send me a file so I can check that?

**Comment by skynetua** [comment]
Sent to email

**Comment by skynetua** [comment]
I propose to add lib https://code.google.com/p/juniversalchardet/ to get exact encoding of string and than just encode it to UTF-8. What do you think?

**Comment by Ph1b** [comment]
I dont fully understand this.

I downloaded an example cyrillic file [here](http://www.lastfm.de/music/+free-music-downloads/russian) and it displays the correct characters.

And I found [this](http://www.cloudbeatsapp.com/how-to-fix-japanese-chinese-or-cyrillic-characters-in-mp3-files/) help page from beats audio, which leads me to the direction that the encoding of the files might be wrong?

**Comment by skynetua** [comment]
Cyrillic file you downloaded coded with UTF-8 alredy, i suppose.
I also tried with few players on android and don't see correct characters in mine file. In players for windows it looks ok.

**Comment by Ph1b** [comment]
Ad I don't want additional dependencies this is a wontfix. :(
