### ISSUE TITLE
Playback issue

### ISSUE THREAD

**Issue by skynetua** [Ph1b/MaterialAudiobookPlayer#276]
Playback can't be continued after pressing stop in notification.

Scenario:
1. open some book.
2. press play.
3. open notification area and press Stop
4. press play in application.

Problem:
Playback is stuck and can't be continued until force stop application in settings.

**Comment by Ph1b** [comment]
What do you mean by stop? Which android version are you using?

**Comment by skynetua** [comment]
That:
if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
      notificationBuilder.addAction(R.drawable.ic_close_white_36dp, getString(R.string.stop), stopPI);
}

**Comment by Ph1b** [comment]
Is this reproducible? With different songs? On my Kitkat and Lollipop devices it works as intended.

**Comment by skynetua** [comment]
I am able to reproduce it on emulator with api16 with additional steps. After step 4 I had delay 5-7 sec before playback starting. While that delay I pressed Back and than pressed Play fab on shelf activity. After that player stuck.
However few peoples have that problem exact after step 4 in initial scenario.

**Comment by skynetua** [comment]
Looks not reproducable after 3b0b3124c9df5ae65c2b76026061500dbfe8f9ca
