### ISSUE TITLE
Chapter support for .m4b Audiobook files

### ISSUE THREAD

**Issue by sparomba** [Ph1b/MaterialAudiobookPlayer#282]
Please add chapter support for .m4b Audiobook files. Currently it's only possible to fast forward/backwards or jump to a specific, time based, location.

.m4b Audiobook files usually come with Chapter indicators (ex. "Chapter 3 - The title of this chapter") of the actual book. It would be a nice feature just list the chapters and jump to them.

For reference, the feature is integrated in the "Smart Audiobook Player" app.

**Comment by Ph1b** [comment]
Duplicate #205
