### ISSUE TITLE
[Feature Request] Play all audiobooks in the library sequentially

### ISSUE THREAD

**Issue by nvx2004** [Ph1b/MaterialAudiobookPlayer#283]
I have a single folder called "Audio" on my phone where I put podcasts and audiobooks. In the player I have added this folder as "multiple audiobook folder" so that I see all the items separately with their respective titles etc. extracted from tags, not as a single audiobook with title set according to the first file in the folder. This, however, requires me to manually start playback of each and every one of the podcasts/audiobooks. What I would therefore very much like to do is start playing back the first file (i.e., the first item in the library) and then having the player take one file after another and play them sequentially.

Thank you.

**Comment by Ph1b** [comment]
I neither want to confuse users, nor add another settings to the list. I think this is a feature a minority will use, so no, sorry.
