### ISSUE TITLE
List View in addition to Cover View

### ISSUE THREAD

**Issue by nvx2004** [Ph1b/MaterialAudiobookPlayer#284]
It would be great if List View (i.e., one audiobook per line) were available for the Library in addition to Cover View. This way more items would fit onto the screen and one would not have to scroll so much.

The List View would not have to be anything fancy -- just e.g. a _small_ cover image (or even no cover image at all for a more condensed view) and the respective audiobook title for each item.

Thank you.

**Comment by Ph1b** [comment]
Implemented as of 7ad76b38e161c4e15dcef76a409e81986a88157c

**Comment by kevmitch** [comment]
Very nice. Thanks.
