### ISSUE TITLE
Add "listened" marker to allready consumed audiobooks

### ISSUE THREAD

**Issue by mr-gosh** [Ph1b/MaterialAudiobookPlayer#286]
Like in kodi - it would be awesome to have a "allready listened" marker - to get an idea which booksbgot allready listened. 
In addition there could be a "hide listened books" option in settings - that hides allready completely listened books and also marks allready partly consumed audio books...

**Comment by Ph1b** [comment]
Should be implemented by the list progress as of 38d3e2714cfdb8587662f3f1259c1cd39a74ec4e
