### ISSUE TITLE
More detailed widget

### ISSUE THREAD

**Issue by justaperegrine** [Ph1b/MaterialAudiobookPlayer#289]
Dear Paul,

Thank you for this beautiful application again, and here is my suggestion:

_____________________________________________________________________________

in a 4x1 widget setting the objects A B C D;

A:for left and right symmetrical ends, "two high buttons" to browse between the folders that are added to the audiobook player.

B:next is symmetrical "two round low buttons" in the inner ends for 'audio file browsing'

C:next is symmetrical "two round low buttons" intter ends for fast backward and fast forward of current audio file.

D:in the middle a relatively fatter round button to play/pause

E:as seen on the picture there is a slim line on the top of B,C,D objects, maybe cutted in half showing the folder name | audio file

![widget suggestion4x1](https://cloud.githubusercontent.com/assets/8126485/9525720/26a710c8-4cee-11e5-9fe2-040ef1f7b4a6.jpg)

____________________________________________________________________________

in a 3x1 widget setting:

object C , seems only one part of E could be included considering the space given.

![widget suggestion3x1](https://cloud.githubusercontent.com/assets/8126485/9525719/2693d03a-4cee-11e5-894c-c3662015904a.jpg)

As a summary, having /the browsing the audio folder/audio file/and maybe fastforward/backward features is not an easy thing to do. However, I believe It's not impossible. If it seems too hard, a more compact thing might be in following priority

___________________________________________________________________________

alternative minimalism :)

1.play/pause
2.browse between added folders (yes!:))
3.browse files inside the audio folder only forward!
4.a fast forward button (makes a +30 seconds or such..)
5.a slim string like showing the album or folder name.

this is the end of the suggestion. Thank you for reading. and I wish you all the best..

**Comment by Ph1b** [comment]
I prefere the minimal way it is now with the dynamic resizing. The widget should give you quick controls. For the full featured navigation is the general UI.
