### ISSUE TITLE
Material player (widget?) hogging media buttons on lollipop / cm12

### ISSUE THREAD

**Issue by yaymeh** [Ph1b/MaterialAudiobookPlayer#290]
Not sure how, but material player (/the widget) always seems to gets the media buttons in lollipop / cm12. Even if the main app isn't running, even while the stock music player is already open, in plain view, playing music.

I also pitted material player against "media button router" and material player always won. The only way to use media buttons for anything else seems to be rebooting the device and being careful to not touch the widget.

**Comment by jnordstrom90** [comment]
Might this be related to the always on widget service? http://imgur.com/wwPDnlZ
This without having started the player since last boot and even no book in progress

**Comment by Ph1b** [comment]
Which android version do you use?

I cannot confirm this. When paused it still receives the events. When stopped (swipe the notification away) it does not. (Tested on Android 5.0.0)

**Comment by yaymeh** [comment]
Ooops... I have the notification disabled (it kind of took up a lot of space -.-" ), so I wasn't aware that turning it all the way off like that was even an option. 

I guess this means, this is intended behaviour and I should change the issue into a feature request?

Would be great to have a setting to optionally disable the persistent reacquiring of the media button control while playback is paused, allowing other apps to take over if they try to get button control during "pause". I'm probably not the only one who uses both material player and a music player while driving and fiddling with the notifications area definitely isn't something I'd want to do on the road. 

( Using Android 5.1.1 )

**Comment by Ph1b** [comment]
Yes, that is intended behavior. Sorry but in this case you have to swipe the player away if you don't want to have him receiving controls.
That is the concept of paused, that it is not stopped and is ready to be resumed.

**Comment by yaymeh** [comment]
Didn't manage to get my car close enough to my PC to view the logs of what exactly is happening, but what I can say for sure is that swiping the player away (instead of just pausing) does not seem to make a difference at all. Material player (/widget) is still interrupting other apps.

Tested multiple times:
- Connected to car radio via Bluetooth. Material player starts playing. 
- Paused material player widget, opened notifications area and swiped it away.
- Started music player, double-checked that music player is present in notifications and that material player is NOT.
- Pressed play button. Music player stopped playing, material player started playing instead. 
- Rebooted phone, started music player. Play buttons work fine with music player.
- After using material player widget again, there - yet again - seemed to be no other way to give control back to the music player other than rebooting the phone.
