### ISSUE TITLE
Request support for .Zab file format

### ISSUE THREAD

**Issue by untermensch** [Ph1b/MaterialAudiobookPlayer#292]
I stumbled across the zipped audio book format a few weeks ago, and it seems like a cool idea.

**Comment by Ph1b** [comment]
Zab is not part of the android fragmework and therefore I cannot add support for it.

**Comment by corani** [comment]
ZAB is merely a renamed ZIP file. The Android Framework *does* support ZIP files (see e.g. java.util.zip.ZipFile)

**Comment by pjvleeuwen** [comment]
5 years later I would like to ask to reconsider this request made by @AR1972 and @corani : any chance you can add this feature?

**Comment by test2a** [comment]
Seconded. I have many books in zab (zip) format and I have to extract it first and then continue.

**Comment by pjvleeuwen** [comment]
@PaulWoitaschek mentioning you, since I am not sure if otherwise above comment reaches you. for your consideration
