### ISSUE TITLE
Add possibility to refresh audiobook folder

### ISSUE THREAD

**Issue by thigg** [Ph1b/MaterialAudiobookPlayer#293]
VLC for android is able to play m4a files, but it would be awesome to have it in Material too.

**Comment by Ph1b** [comment]
The format m4a should be supported right now. What happens if you try to add a book and play it?

**Comment by thigg** [comment]
Ah, actually it worked when it discovered the files. My problem was that the folder didn't show up, so I thought its not able to play m4a. Would be nice to have a button to refresh or something.

**Comment by Ph1b** [comment]
It is refreshing automatically on every start.
