### ISSUE TITLE
bug; multiple broadcast intents during playback

### ISSUE THREAD

**Issue by circledot** [Ph1b/MaterialAudiobookPlayer#307]
It seems that the playback intents are being repeatedly broadcast during playback.

While I'm here, I'd also like to suggest an option to enable / disable the broadcasting of playback intents.  I do like the intents but sometimes I don't want them broadcast.

Thanks

**Comment by Ph1b** [comment]
You mean these two, right?

        METADATA("com.android.music.metachanged"),
        PLAYSTATE("com.android.music.playstatechange");

That is necessary due to the time of the track is being reported.

**Comment by circledot** [comment]
I'm pretty sure the intents should not be continuously broadcast.  Sure, send an intent with UI interacttion (pause / play), but not continuously.  I have Tasker setup to relay these intents and this app is useless while it's repeatedly and unnecessarily broadcasting them.  Tell me the use case for their repeated broadcast when there is no UI interaction?

**Comment by Ph1b** [comment]
#190

**Comment by circledot** [comment]
Personally, I use the intents with Tasker.  Some apps that use the intents are Vanilla Music and SoundCloud.  Both apps (and others) broadcast the track when it is played / resumed, but not continuously, every second or so.  It would be great and appreciated if this could be fixed.

**Comment by Ph1b** [comment]
That way the time wont show up. And I assume most of the users prefer it the way it works now.

**Comment by circledot** [comment]
Sorry, I don't understand your last comment.

**Comment by Ph1b** [comment]
It means that I don't see disadvantages in sending intents with the correct position.

**Comment by circledot** [comment]
Why has the position got to be broadcast through intents?  SoundCloud doesn't do that yet it has positioning and time-based commets etc.

If I want to relay those intents over the net, it eats into data and is generally wasteful / inefficient.  Server side, it's problematic, especially considering all these other apps are behaving as expected.
