### ISSUE TITLE
Copyright violation by company called Nekend?

### ISSUE THREAD

**Issue by Ph1b** [Ph1b/MaterialAudiobookPlayer#313]
By mail:

>Hi,

>Just a small heads up from a fellow developer.
This guy might be violating your source-code license by just reuploading your app and removing all references to you and the original app & code.
https://play.google.com/store/apps/details?id=com.fibox

>The screenshots don't show it but if you download it, it's your audiobook player.

>Best regards

>Matthias

Results of a little research:
Website: http://nekend.com/
Address: Carretera B-19 (Cieza-Calasparra) Nº38
Picture from the website: http://nekend.com/file/2015/02/desat-boy-m4-180x1801.jpg
Mail: joselikoxulo@hotmail.com

**Comment by joseliko7** [comment]
Hello, Nekend is my study. 
I do not want problems.

Currently Fibox is a simple check Google application user interface designs with a small set of commands that connects to the music library.

The source code is a UI of Google (Google Design) My friend helped me set the rules and more.
