### ISSUE TITLE
Consult

### ISSUE THREAD

**Issue by joseliko7** [Ph1b/MaterialAudiobookPlayer#314]
![2](https://cloud.githubusercontent.com/assets/13633032/10100608/336a1ed4-6393-11e5-8814-314fd03fb044.jpg)
Every day I learn more of your wonderful code but I have a question.

When I try to change the package name tells me that there is already a package named com.

How can I do it?

Thanks!

**Comment by Ph1b** [comment]
For basic development help please consult a website like [stackoverflow.com](https://stackoverflow.com/).
