### ISSUE TITLE
Cannot play .opus files

### ISSUE THREAD

**Issue by micressor** [Ph1b/MaterialAudiobookPlayer#316]
Playing of audiobooks in [.opus format](https://en.wikipedia.org/wiki/Opus_%28audio_format%29) does not play proper. Signal noise!

Tested on [CyanogenMod 12.1](https://en.wikipedia.org/wiki/CyanogenMod#CyanogenMod_12.1) (based on Android 5.1).

How can I help to fix that?

Thanks.

**Comment by joseliko7** [comment]
):

**Comment by Ph1b** [comment]
#310
