### ISSUE TITLE
Suggestion // Adding 'Play' at Library-View

### ISSUE THREAD

**Issue by JoshGraham** [Ph1b/MaterialAudiobookPlayer#319]
If 'Play' is added above 
//
Edit name
Edit cover
Bookmark
//

User might choose to play another audiobook which is not already playing, at the Library-View, without going into the new album-view and tapping on 'Play' button.

Thus, saving a tap.

**Comment by Ph1b** [comment]
Tap is not saved due to a necessary click on the dots.

**Comment by JoshGraham** [comment]
You're right.

Coming to think of it, it won't, save a tap.

Haha, what is this? I've fooled myself. ;)
