### ISSUE TITLE
File length issue

### ISSUE THREAD

**Issue by DracoZaroff** [Ph1b/MaterialAudiobookPlayer#323]
Certain mp3 files show as being over 6 hours long when they are actually less than 3 hours long. 
This causes the playback to jump back quite far whenever playback is interrupted. 
I can provide one or more of the files to recreate the issue upon request.

**Comment by Ph1b** [comment]
An example file would be really helpful. Either you upload it here or send it to my mail (in my profile).

**Comment by Ph1b** [comment]
I checked the file and it seems to be corrupt. 
The default music player doesn't even play the file you sent me. Same with Google Music. Can you play it with other players?

**Comment by DracoZaroff** [comment]
I played it without issue and with the correct length displayed on VLC. But
to be sure now that you mentioned it, I checked with other players and each
gives the same issue as we see with Material player.
I suppose I should have checked with multiple players to begin with rather
than just initially using VLC. I wonder if VLC uses a different method to
estimate the file's length.
Sorry about that.

**Comment by Ph1b** [comment]
I don't know how but VLC plays most of the files out there fine, no matter how corrupt they are.

There was an earlier release where MAP used the technical base of VLC but many people had problems with that. When it's more stable we might switch to vlc one day.
