### ISSUE TITLE
No folders selectable

### ISSUE THREAD

**Issue by DeckardCain2014** [Ph1b/MaterialAudiobookPlayer#330]
In the recent version of the Player in combination with Android 6 on a Nexus 5; no folders are selectable. Permission for folder access is asked and granted...

**Comment by Ph1b** [comment]
Which version are you using? A preview one?

**Comment by DeckardCain2014** [comment]
No, current 6.0.0 (MRA58K)

**Comment by Ph1b** [comment]
That's weird. Because thats where it should have been fixed. See [this report](https://code.google.com/p/android-developer-preview/issues/detail?id=2982)

**Comment by Ph1b** [comment]
Btw if you kill the app and restart it then it should work.

**Comment by DeckardCain2014** [comment]
Okay, reinstalling and then force killing after granting fixes it ;) Thanks for quick response!!

**Comment by Ph1b** [comment]
Reinstalling should not have been necessary.

**Comment by icy32** [comment]
It's fixed in MRA58K, but it depends on how you performed the update. Did you get an OTA update or did you flashed factory image ?

**Comment by soboapps** [comment]
I see the same thing on my Nexus 6 w/ Marshmallow (OTA).  It only happens on first launch.  After you have allowed the permissions and then go back and then back in to select a folder, they show up.

**Comment by Ph1b** [comment]
The guidelines say to ask when it is needed. And it seems to work for the normal OS upgrade.

**Comment by soboapps** [comment]
Your Project...  But as I said, I see the exact same behavior on my Nexus 6 running Stock Android 6 (Sprint OTA from Lollipop), doing a Clean Install of the App.  The first time it asks to set the Folder and ask for Permissions, It is not showing any folders.  In my instance, I have to close the app and relaunch it.  At that time I see the folders.

**Comment by Ph1b** [comment]
Can you @soboapps  check if this still occurs in the [latest nightly](https://github.com/Ph1b/MaterialAudiobookPlayer/releases/tag/nightly-2015-11-28-2)?

**Comment by soboapps** [comment]
It is now working correctly.  Thanks!

**Comment by WACMemphis** [comment]
@PaulWoitaschek Can you let me know what it is you changed in that nightly build that made it work? I'm experiencing the exact same problem in my app and I can't seem to resolve it.

**Comment by PaulWoitaschek** [comment]
@WACMemphis The 'fix' is to include `/storage` as a storage from Android M on.

**Comment by WACMemphis** [comment]
@PaulWoitaschek So that's unrelated to `READ_EXTERNAL_STORAGE` not working as expected?

**Comment by PaulWoitaschek** [comment]
It depends. Here it is not clear what caused the issue.

There is one issue about the path not showing up: #349 
And there is an issue about M preview devices [here](https://code.google.com/p/android-developer-preview/issues/detail?id=2982&q=Type%3DDefect&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars).

**Comment by WACMemphis** [comment]
The second link is exactly what I'm experiencing and also how I found your app. It's happening on a non-preview M device for me though. Was hoping you'd have figured out how to get around it.

**Comment by PaulWoitaschek** [comment]
You could try using [Process Phoenix](https://github.com/JakeWharton/ProcessPhoenix) from Jake Wharton after getting the callback. That's a bit dirty, but if you really have to work around this...

**Comment by WACMemphis** [comment]
@PaulWoitaschek Well, I don't see what else I could do. I'm requesting the permission as described in the guidelines and only once I get it, I try to write to the external storage. This fails the first time around, but succeeds after you restart the app, which really isn't ideal.

**Comment by PaulWoitaschek** [comment]
That is why I suggested to restart the process manually so you don't have to bother the user.

After getting the callback check if you can read and if not, then... Phoenix!

**Comment by WACMemphis** [comment]
@PaulWoitaschek That'll have to be my last resort, as the attempt to save is part of a user interaction. Restarting during this process will be very confusing for the user. Thanks anyway!

**Comment by PaulWoitaschek** [comment]
You can specify an intent using phoenix. So:

1. Request
2. Check if you got the permission
3. Check if you can read now
4. If not, gather all user input
5. Put stuff in a bundle
6. Create an intent with that bundle leading to where you are
7. Give that intent to phoenix so you land exactly where you were

**Comment by WACMemphis** [comment]
Alright, that sounds less bad. I still don't get why this is necessary. Requesting the write permissions, receiving it and then writing should just work... Thanks for your help again.

**Comment by PaulWoitaschek** [comment]
Because we are Android developers and Android is full of bugs. Our job is it to find workarounds :D
