### ISSUE TITLE
Suggestion: Launch and autoplay when headphones are set

### ISSUE THREAD

**Issue by uplapps** [Ph1b/MaterialAudiobookPlayer#333]
First of all, thanks a lot for this great app.
I think it'd be great to add the possibility in different checkboxes of:
1. Launch the app when the headphones are set
2. Autoplay when the headphones are set
Thanks again and good luck!

**Comment by kevmitch** [comment]
if by "set" you mean plugged in, 

2. already works with the "resume playback" option in MAP preferences.

**Comment by kevmitch** [comment]
The fix suggested in #344 will probably make 2. work if you configure it in Android system settings.

**Comment by Ph1b** [comment]
Thanks for the suggestion. I think it's to intrusive to catch all headset plug-ins and start playing then.

What you can do is check the settings to resume on replug. That way you have the desired behavior but only when the player was paused by plugging the headset out.
