### ISSUE TITLE
When I tap an MP3 file, I see an app selector; please show Material Audio Player among the choices

### ISSUE THREAD

**Issue by unforgettableid** [Ph1b/MaterialAudiobookPlayer#344]
My file manager is "OI File Manager".  When I tap on a .mp3 file, Android shows me a "Complete action using" box which lets me choose an audio player to use -- VLC, AntennaPod, et cetera.

Material Audiobook Player is unfortunately not one of the choices.

It would be good if you could please make it be one of the choices.

(I'm using Material Audiobook Player 2.4.2 on Android 4.1.2 on a Samsung Galaxy S Relay 4G.)

P.S.  Thank you very much for writing and maintaining Material Audiobook Player, and for releasing it as open-source.

**Comment by soboapps** [comment]
I added this to the Manifest to the BookActivity and it now show the player as an option in the Open With

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:scheme="file" />
                <data android:mimeType="audio/*" />
                <data android:pathPattern=".*\\.mp3" />
                <data android:pathPattern=".*\\.m4a" />
                <data android:pathPattern=".*\\.m4b" />
            </intent-filter>

**Comment by unforgettableid** [comment]
Cool!  Thank you very much for so quickly implementing this; I look forward to using it after the next release hits the Google Play store.  :)

**Comment by soboapps** [comment]
I wouldn't call this official...  I'm just saying what "I" did to make this work.  This is not my Project.

**Comment by unforgettableid** [comment]
Ah, my mistake.  I thought you were a committer, and were telling me about a commit you'd made.

Though, if you did send the Material Player maintainers a pull request, it would be most excellent :)

Reopening.

**Comment by Ph1b** [comment]
This is not the way books are handled. It has to be added manually in the book chooser progress. The internal structure would need a very large rewrite to have these kind of 'temporary books'.
So as the benefit would be quite little for an audiobook app this won't be implemented, sorry.

The intent filter above simply opens the app and does nothing else.

**Comment by unforgettableid** [comment]
No matter.  As a workaround, I can use AntennaPod when I want to open a file I see in my file manager.  It also has good support for jumping forwards and backwards in 10-second increments.
