### ISSUE TITLE
Add Repeat Function

### ISSUE THREAD

**Issue by soboapps** [Ph1b/MaterialAudiobookPlayer#345]
The ability to put a short book or audio file on repeat.  I have small children and I record myself reading them a book and when I am on travel, they can play it back on a tablet and flip the pages (A little help from Mom), but they love to play it multiple times, having a button to automatically repeat would be Great. Kinda a Audiobook/Music player hybrid... I have not been able to find an Audiobook player with this function and Music players look for all media and this apps allows me to restrict folders.  The functions of this player is perfect except for this missing piece.

**Comment by soboapps** [comment]
I have been trying to set this up myself, but I can not figure out where to put .setLooping(true)
I have tried player.setLooping(true); and it acts as if it has no clue what .setLooping(true) is.  The only way I could get .setLooping(true) to show up was to create my own instance of MediaPlayer, which of course didn't work.  If you can point me in the right direction, I might be able to figure it out.  Thanks!

**Comment by Ph1b** [comment]
I think this is not one of the core features of audiobook players and would be useful for a minority of users. So this won't be implemented.
Also there is no setLooping implemented. What you could do is go in the Dagger Module, return always an Android Media Player, add the looping method to the MediaPlayerInterface, let the CustomMediaPlayer implement it as a stub and then use the normal MediaPlayer to have the looping feature enabled.
