### ISSUE TITLE
SUGGESTION: Bookmark with one touch

### ISSUE THREAD

**Issue by BoringUserWhoCantCode** [Ph1b/MaterialAudiobookPlayer#348]
Listening to an audiobook, I'd like to have an option to "bookmark with one click" instead of having to supply a name for each bookmark.

I just want to save a bookmark with the latest point. I don't care about its name.

**Comment by Ph1b** [comment]
If you add a bookmark you can do this without entering a name by just clicking on the plus. 

This is a two-click solution but I don't want to provide an alternative way of adding a bookmark as I want to keep it as simple as possible.
