### ISSUE TITLE
No way to delete files

### ISSUE THREAD

**Issue by arzenthal** [Ph1b/MaterialAudiobookPlayer#354]
I have notices that there is no way to delete an audio file in the app. The only way is with an external browser. Will you add a control to delete files?

Thanks for your help and work.

Iván

**Comment by Ph1b** [comment]
Nope, this should not become a file manager.

**Comment by arzenthal** [comment]
OK, understood. Thanks for the reply.

**Comment by jfml** [comment]
Could you maybe reconsider your stance on this? Especially if you are listening to podcasts it's pretty tedious to open up a file manager, navigate to the right folder and then delete the file from there after you listened to it as opposed to maybe two clicks from within the app. I'd really love to have this feature.
