### ISSUE TITLE
Service remains active when not in use

### ISSUE THREAD

**Issue by rejhgadellaa** [Ph1b/MaterialAudiobookPlayer#355]
service remains active when the app hasnt been used for >65hrs?

Also reportes it via settings so there should be a report inbound via play store dev console

**Comment by Ph1b** [comment]
Why is that a problem? Do you face any battery issues?

**Comment by rejhgadellaa** [comment]
Not sure if it uses battery but it does use memory..? I haven't looked at the code (yet) but could if android kills the service for memory it doesn't call onDestroy (at least not in my personal experience) so if there are important calls in there like storing playback position stuff is lost.

I'll have a look when i get home. +1 for the quick reply :)

**Comment by Ph1b** [comment]
Still not home?

Once the android OS needs memory it should kill the service. And onDestroy is usesd to release sources not to save some state as it is not guaranteed to be called. (like you said).

**Comment by rejhgadellaa** [comment]
Sry I had a quick look yesterday but didn't have time to really follow all the calls in ondestroy. I think I'll just take your word for it :)

I only noticed it was still running because greenify showed it so it's not like I was experiencing battery issues or whatever. I assume your reason for keeping the service alive is that as long as android doesn't need the memory it's not a problem to have it around (kind of how android handles memory in the first place?)

Anyhow, again thanks for the reply. I just wanted to bring this under your attention in case it wasn't "as designed". Great app, btw, I love it :D
