### ISSUE TITLE
Adding multipane tablet layout

### ISSUE THREAD

**Issue by Ph1b** [Ph1b/MaterialAudiobookPlayer#38]
topic

**Comment by M3tthew** [comment]
Widget from time to time still not responding. not dying like previously but sometimes i need to tap about 6-7 time for starting playing

**Comment by Ph1b** [comment]
Please  post bugs in separated issues.

**Comment by M3tthew** [comment]
this one is closed already

**Comment by Ph1b** [comment]
Ill reopen closed posts when someone posts and it is necessary. But you can just open a ticket since this bug looks different.
