### ISSUE TITLE
My  Suggestions

### ISSUE THREAD

**Issue by M3tthew** [Ph1b/MaterialAudiobookPlayer#79]
Thanx for adding m4b copability. And here is my few comments. 1. It loading files when i choose a folder a beat slow, other players do it faster. 2. When i pick a folder it says i need to choose which file to load from folder, why i t don't load all of them to player library? and then i can choose which i want t play. 3. Changing playback speed is very important o please fix it or redo. 
And also if you want i can draw for you a new logo for this player with a philosophy of material design for free

**Comment by Ph1b** [comment]
done
