### ISSUE TITLE
Few Suggestions

### ISSUE THREAD

**Issue by ashruv** [Ph1b/MaterialAudiobookPlayer#80]
Hello developer,
first I want to say, thank you very much for developing for us! 
second, I have few suggestion I believe many would appreciate:
a. add a "bookmark" option. and an auto-bookmark option when you close the app and when the sleep timer is done.
b. for the sleep timer, I could very much use an option to sleep when chapter ends, not by time. maybe other will too :)
c. 3 kinds of skip buttons: short skip, longer skip and chapter skip.

thanks again for your work, hope you will understand the importance of these suggestions.
Ash.

**Comment by lightonflux** [comment]
Or if you are in school need to read a book and you are lazy and just listen to the audiobook. When you write your review it would be quite handy to add bookmarks while listening.

**Comment by Ph1b** [comment]
Please open separated tickets for different requests. Bookmarks are on the way to being implemented.
