### ISSUE TITLE
Automatic rewind after pause

### ISSUE THREAD

**Issue by emansije** [Ph1b/MaterialAudiobookPlayer#87]
It would be great if the player could rewind a bit, after resuming play. How much it rewinds would depend on the length of the pause, up to a predefined maximum. For instance, it could rewind 2 seconds after a very short pause and up to 20 seconds after a long one.

**Comment by MuchosMuffins** [comment]
Would like to see this! 10 seconds rewind or variable!

**Comment by Yma981** [comment]
+1

**Comment by innesst** [comment]
I note that the new behavior is to pause each time there is sound request from another app (email notification, navigation, phone call). The rewind behavior should not happen for a "bing" that you have a text as that is a less than 1 second interruption typically. 

In other programs, I have seen the rewind only after you manually pause, exit, or phone call. I agree with this as the other interruptions are typically too short to warrant a rewind.

**Comment by Ph1b** [comment]
Implemented as of fe41c4335d25c2c42448b27eca691fe6549bf711

**Comment by RafailFridman** [comment]
Are there any plans to implement the rewind amount being dependent on the pause time?
