### ISSUE TITLE
Feature request: Time information

### ISSUE THREAD

**Issue by Yma981** [Ph1b/MaterialAudiobookPlayer#95]
10x for the wonderful App

Please can u add a live line describing the time as following:

Example:
Read 15 of 27:15:45 1% Left: 27:00:45

Read: Total time read so far.
27:15:45  Total time of the whole book (Sum of the time of all parts)
1%: percentage read so far
Left: (total time of the book) - (time read so far)

Thanks

**Comment by Ph1b** [comment]
I dont want to fill the player with features not absolutely necessary. If you need an approx position, just open the spinner and the slider on the right will show you where you are at the moment.
