### ISSUE TITLE
Feature request: Remember playback speed

### ISSUE THREAD

**Issue by Groundrunner** [Ph1b/MaterialAudiobookPlayer#96]
First of all thank you for an absolutely amazing, clean and simple audiobook player. I hope you will be able to keep it as clean as it is now.

Now for my feature request; I would find it beneficial, if the player would remember the playback speed. At the moment, when you exit the app and start it again, the playback speed is reverted back to x1.00.

Thank you for the consideration.

**Comment by Ph1b** [comment]
Implemented as of e544d7d47a0970ceb51c576798bed7d37f2dd9d8
