### ISSUE TITLE
Adding Audiobooks fails silently

### ISSUE THREAD

**Issue by karottenreibe** [Ph1b/MaterialAudiobookPlayer#99]
I have 4 very long Audiobooks (each about 3-4 files with 6 hours each).  I managed to add 1, but the others just show the Spinner for a long time. When I come back to my phone, the spinner is gone and the book wasn't added.

**Comment by Ph1b** [comment]
Can someone confirm this problem? For me it works. I just added 2 books > 10h and it took less than an hour, so Im wondering what have gone wrong.

**Comment by Yma981** [comment]
Dear Ph1b, every time I add a book the App crashes.
I close it and reopen it, the book appears in the list of added books

**Comment by Ph1b** [comment]
Did you report the bug via the crash message?

**Comment by Ph1b** [comment]
As there are no more reports, I guess this is resolved. If not, please reopen.
